# Generated by Django 6.0.1 on 2026-01-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
