# Generated by Django 6.0.1 on 2026-01-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_course_options_alter_course_unique_together_and_more'),
        ('students', '0003_remove_student_enrollment_no_alter_student_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.department'),
        ),
    ]
