# Generated by Django 5.2.10 on 2026-01-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_professor_department_alter_course_department_and_more'),
        ('colleges', '0006_remove_college_admin_user_college_is_active'),
        ('students', '0005_alter_student_department'),
        ('university', '0002_faculty_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_degree', to='academics.degree'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_college', to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to='university.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_program', to='academics.program'),
        ),
    ]
