# Generated by Django 5.2.10 on 2026-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_aadhar_no_student_caste_student_hindi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mdc_course',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
