# Generated by Django 5.2.11 on 2026-03-21 20:51

import omr.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(upload_to=omr.models.omr_upload_path)),
                ('part', models.CharField(choices=[('C', 'Part C — Evaluator'), ('D', 'Part D — Student Info')], max_length=1)),
                ('mode', models.CharField(choices=[('cv', 'Computer Vision'), ('ai', 'AI Vision')], default='cv', max_length=2)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=12)),
                ('error_msg', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('center_code', models.CharField(blank=True, max_length=10)),
                ('course_code', models.CharField(blank=True, max_length=15)),
                ('roll_number', models.CharField(blank=True, max_length=15)),
                ('year', models.CharField(blank=True, max_length=2)),
                ('sem', models.CharField(blank=True, max_length=2)),
                ('session', models.CharField(blank=True, max_length=10)),
                ('exam_type', models.CharField(blank=True, max_length=20)),
                ('sitting', models.CharField(blank=True, max_length=10)),
                ('ug_old', models.CharField(blank=True, max_length=10)),
                ('ug_new', models.CharField(blank=True, max_length=10)),
                ('pg_sem', models.CharField(blank=True, max_length=10)),
                ('faculty', models.CharField(blank=True, max_length=20)),
                ('marks_obtained', models.CharField(blank=True, max_length=5)),
                ('total_marks', models.CharField(blank=True, max_length=5)),
                ('json_result', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OMR Scan',
                'verbose_name_plural': 'OMR Scans',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
