# Generated by Django 5.2.12 on 2026-03-22 10:52

import django.core.files.storage
import omr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrscan',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/omr_uploads/', location='omr_uploads'), upload_to=omr.models.omr_upload_path),
        ),
        migrations.AlterField(
            model_name='omrscan',
            name='sem',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='omrscan',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
