# Generated by Django 5.2.12 on 2026-03-31 18:53

import django.core.files.storage
import omr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omr', '0003_omrscan_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrscan',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/omr_uploads/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\omr_uploads'), upload_to=omr.models.omr_upload_path),
        ),
    ]
