# Generated by Django 5.2.11 on 2026-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bba_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbacoursestructure',
            name='label',
            field=models.CharField(blank=True, choices=[('CIA', 'CIA'), ('ESE', 'ESE')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bbastudentassessment',
            name='label',
            field=models.CharField(choices=[('CIA', 'CIA'), ('ESE', 'ESE')], db_index=True, max_length=200),
        ),
    ]
