# Generated by Django 5.2.10 on 2026-03-17 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGCenterInstituteMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from staging', max_length=50, null=True)),
                ('center_code', models.CharField(blank=True, max_length=255, null=True)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('session_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sem', models.CharField(blank=True, max_length=255, null=True)),
                ('copied_from_staging', models.BooleanField(default=True, help_text='Copied from staging.CenterInstituteMapPurnea')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PG Center Institute Map',
                'verbose_name_plural': 'PG Center Institute Maps',
                'indexes': [models.Index(fields=['center_code'], name='pgoldresult_center__8974fd_idx'), models.Index(fields=['institute_code'], name='pgoldresult_institu_3edd85_idx'), models.Index(fields=['course_code'], name='pgoldresult_course__fb66d8_idx'), models.Index(fields=['batch_code'], name='pgoldresult_batch_c_b1049d_idx'), models.Index(fields=['session_code'], name='pgoldresult_session_7fe1d9_idx')],
            },
        ),
    ]
