# Generated by Django 5.2.10 on 2026-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0002_pgcenterinstitutemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgoldresult',
            name='pg_degree',
            field=models.CharField(blank=True, help_text='PG Degree name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pgoldresult',
            name='pg_department',
            field=models.CharField(blank=True, help_text='PG Department name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pgoldresult',
            name='pg_faculty',
            field=models.CharField(blank=True, help_text='PG Faculty name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pgoldresult',
            name='pg_program',
            field=models.CharField(blank=True, help_text='PG Program name', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='pgoldresult',
            index=models.Index(fields=['pg_faculty'], name='pgoldresult_pg_facu_c67a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='pgoldresult',
            index=models.Index(fields=['pg_department'], name='pgoldresult_pg_depa_449e41_idx'),
        ),
        migrations.AddIndex(
            model_name='pgoldresult',
            index=models.Index(fields=['pg_degree'], name='pgoldresult_pg_degr_8771b3_idx'),
        ),
        migrations.AddIndex(
            model_name='pgoldresult',
            index=models.Index(fields=['pg_program'], name='pgoldresult_pg_prog_41d72c_idx'),
        ),
    ]
