# Generated by Django 5.2.10 on 2026-03-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0003_pgoldresult_pg_degree_pgoldresult_pg_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgoldresult',
            name='college_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
