# Generated by Django 5.2.10 on 2026-03-18 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('pgoldresult', '0004_pgoldresult_college_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgoldresult',
            name='college_name',
        ),
        migrations.AddField(
            model_name='pgoldresult',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College reference from colleges app', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_old_results', to='colleges.college'),
        ),
    ]
