# Generated by Django 5.2.10 on 2026-03-19 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('pgoldresult', '0005_remove_pgoldresult_college_name_pgoldresult_college'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGOldStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_no', models.CharField(db_index=True, help_text='College Registration Number (college_reg_no from PGOldResult)', max_length=100, unique=True)),
                ('roll_no', models.CharField(blank=True, help_text='College Roll Number (college_roll_no from PGOldResult)', max_length=100, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_name_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, help_text='Course code: PG, etc.', max_length=50, null=True)),
                ('discipline_code', models.CharField(blank=True, help_text='Discipline code: M21, etc.', max_length=50, null=True)),
                ('pg_faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_department', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_degree', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_program', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=30, null=True)),
                ('current_semester', models.CharField(blank=True, max_length=30, null=True)),
                ('final_result', models.CharField(blank=True, max_length=50, null=True)),
                ('gpa', models.CharField(blank=True, max_length=20, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=20, null=True)),
                ('total_percentage', models.CharField(blank=True, max_length=20, null=True)),
                ('source_user_id', models.CharField(blank=True, help_text='Original user_id from staging', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pg_old_students', to='colleges.college')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_old_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PG Old Student Profile',
                'verbose_name_plural': 'PG Old Student Profiles',
            },
        ),
        migrations.AddField(
            model_name='pgoldresult',
            name='student_profile',
            field=models.ForeignKey(blank=True, help_text='Link to PG Student Profile', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pgoldresult.pgoldstudentprofile'),
        ),
        migrations.AddIndex(
            model_name='pgoldstudentprofile',
            index=models.Index(fields=['registration_no'], name='pgoldresult_registr_850965_idx'),
        ),
        migrations.AddIndex(
            model_name='pgoldstudentprofile',
            index=models.Index(fields=['roll_no'], name='pgoldresult_roll_no_9c21b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pgoldstudentprofile',
            index=models.Index(fields=['college', 'course_code'], name='pgoldresult_college_fe789f_idx'),
        ),
    ]
