# Generated by Django 5.2.10 on 2026-03-20 09:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0006_pgoldstudentprofile_pgoldresult_student_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGExamMasterDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from staging ExamMasterDump', max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_name', models.CharField(blank=True, max_length=500, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('session_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, default='PG', max_length=255, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=255, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_all', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_exam_month', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('sl_no', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_month', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_year', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_mark_entry_date', models.CharField(blank=True, max_length=255, null=True)),
                ('online_payment_transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('omr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('template_code', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_status', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sem', models.CharField(blank=True, max_length=255, null=True)),
                ('copied_from_staging', models.BooleanField(default=True, help_text='Copied from staging.ExamMasterDump where course_code=PG')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PG Exam Master Dump',
                'verbose_name_plural': 'PG Exam Master Dumps',
                'indexes': [models.Index(fields=['exam_code'], name='pgoldresult_exam_co_ce3b51_idx'), models.Index(fields=['batch_code'], name='pgoldresult_batch_c_481fcc_idx'), models.Index(fields=['session_code'], name='pgoldresult_session_4923cd_idx'), models.Index(fields=['semester_code'], name='pgoldresult_semeste_ba4e99_idx'), models.Index(fields=['discipline_code'], name='pgoldresult_discipl_d7b5cc_idx'), models.Index(fields=['institute_code'], name='pgoldresult_institu_4d126b_idx')],
            },
        ),
    ]
