git # Generated by Django 5.2.10 on 2026-03-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0007_pgexammasterdump'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgexammasterdump',
            old_name='publish_status',
            new_name='publish_date',
        ),
    ]
