# Generated by Django 5.2.10 on 2026-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0008_rename_publish_status_pgexammasterdump_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='pgold/profiles/'),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='pgold/signatures/'),
        ),
    ]
