# Generated by Django 5.2.10 on 2026-03-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0009_pgoldstudentprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='caste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='medium_of_student',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pgoldstudentprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
