# Generated by Django 5.2.10 on 2026-03-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0010_pgoldstudentprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgoldstudentprofile',
            old_name='first_name',
            new_name='hindi_name',
        ),
        migrations.RemoveField(
            model_name='pgoldstudentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pgoldstudentprofile',
            name='student_name_hindi',
        ),
    ]
