# Generated by Django 5.2.10 on 2026-03-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0011_rename_first_name_pgoldstudentprofile_hindi_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgoldstudentprofile',
            old_name='student_name',
            new_name='first_name',
        ),
    ]
