# Generated by Django 5.2.10 on 2026-03-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0012_rename_student_name_pgoldstudentprofile_first_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_user_id_005442_idx',
        ),
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_pg_facu_c67a9c_idx',
        ),
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_pg_depa_449e41_idx',
        ),
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_pg_degr_8771b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_pg_prog_41d72c_idx',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='college',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='pg_degree',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='pg_department',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='pg_faculty',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='pg_program',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='user_id',
        ),
    ]
