# Generated by Django 5.2.10 on 2026-03-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0013_remove_pgoldresult_pgoldresult_user_id_005442_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_college_45ed6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pgoldresult',
            name='pgoldresult_college_9b6b7b_idx',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='college_reg_no',
        ),
        migrations.RemoveField(
            model_name='pgoldresult',
            name='college_roll_no',
        ),
    ]
