# Generated by Django 5.2.10 on 2026-03-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgoldresult', '0014_remove_pgoldresult_pgoldresult_college_45ed6f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgoldstudentprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='pgoldstudentprofile',
            name='final_result',
        ),
        migrations.RemoveField(
            model_name='pgoldstudentprofile',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='pgoldstudentprofile',
            name='total_percentage',
        ),
    ]
