# Generated by Django 5.2.10 on 2026-01-22 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0006_remove_college_admin_user_college_is_active'),
        ('students', '0004_alter_student_department'),
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code for the category (e.g., 'academic', 'hostel')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for UI', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text="Color code for UI (e.g., '#FF5733')", max_length=20, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display categories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grievance Category',
                'verbose_name_plural': 'Grievance Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('grievance_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='grievances/attachments/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated to University')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('escalated_to_university', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('assigned_to_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='colleges.college')),
                ('assigned_to_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='university.university')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_grievances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='students.student')),
                ('category', models.ForeignKey(help_text='Category of the grievance', on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='grievance.grievancecategory')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GrievanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment_type', models.CharField(choices=[('comment', 'Comment'), ('status_update', 'Status Update'), ('escalation', 'Escalation'), ('resolution', 'Resolution')], default='comment', max_length=20)),
                ('comment', models.TextField()),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grievances/comment_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievance_comments', to=settings.AUTH_USER_MODEL)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grievance.grievance')),
            ],
            options={
                'verbose_name': 'Grievance Comment',
                'verbose_name_plural': 'Grievance Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['grievance_number'], name='grievance_g_grievan_137837_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['status'], name='grievance_g_status_665803_idx'),
        ),
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['-submitted_at'], name='grievance_g_submitt_2445df_idx'),
        ),
    ]
