# Generated by Django 5.2.10 on 2026-01-22 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this grievance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_grievances', to=settings.AUTH_USER_MODEL),
        ),
    ]
