# Generated by Django 5.2.10 on 2026-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_grievance_deleted_at_grievance_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancecategory',
            name='default_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Default priority for grievances in this category', max_length=20),
        ),
    ]
