# Generated by Django 5.2.10 on 2026-01-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_grievancecategory_default_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievancecategory',
            name='icon',
        ),
    ]
