# Generated by Django 5.2.10 on 2026-01-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_remove_grievancecategory_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='subject',
            new_name='title',
        ),
    ]
