# Generated by Django 5.2.10 on 2026-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0005_rename_subject_grievance_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='student_name',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='title',
        ),
        migrations.AddField(
            model_name='grievance',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
