# Generated by Django 5.2.10 on 2026-01-23 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_rename_student_name_grievance_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='grievancecomment',
            name='attachment',
        ),
        migrations.CreateModel(
            name='GrievanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(upload_to='grievances/attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Optional description of the file', max_length=255, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, help_text='If this attachment is part of a comment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievance.grievancecomment')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievance.grievance')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievance_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grievance Attachment',
                'verbose_name_plural': 'Grievance Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
