# Generated by Django 5.2.10 on 2026-01-23 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0007_remove_grievance_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceattachment',
            name='grievance',
            field=models.ForeignKey(blank=True, help_text='Linked when grievance is created', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievance.grievance'),
        ),
    ]
