# Generated by Django 5.2.10 on 2026-01-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0008_alter_grievanceattachment_grievance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievancecategory',
            name='color',
        ),
    ]
