# Generated by Django 5.2.10 on 2026-01-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0009_remove_grievancecategory_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grievancecategory',
            name='default_priority',
        ),
        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grievancecomment',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
    ]
