# Generated by Django 5.2.10 on 2026-01-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0010_remove_grievance_priority_remove_grievance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='final_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_assigned_to_college',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_assigned_to_university',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_grievance_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievancecategory',
            name='is_assigned_to_college',
            field=models.BooleanField(default=True, help_text='Default to college level handling'),
        ),
        migrations.AddField(
            model_name='grievancecategory',
            name='is_assigned_to_university',
            field=models.BooleanField(default=False, help_text='Default to university level handling'),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], default='open', max_length=20),
        ),
    ]
