# Generated by Django 5.2.10 on 2026-01-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0011_grievance_final_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='escalated_to_university',
        ),
    ]
