# Generated by Django 5.2.10 on 2026-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0012_remove_grievance_escalated_to_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievancecomment',
            name='comment_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('action_update', 'Action Update')], default='comment', max_length=20),
        ),
    ]
