# Generated by Django 5.2.10 on 2026-03-12 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0013_alter_grievancecomment_comment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='is_payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Fixed payment amount for grievance submission', max_digits=10),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='grievance_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='GrievancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Unique order ID sent to CC Avenue', max_length=100, unique=True)),
                ('tracking_id', models.CharField(blank=True, help_text='CC Avenue tracking ID', max_length=100, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='grievance.grievance')),
            ],
            options={
                'verbose_name': 'Grievance Payment',
                'verbose_name_plural': 'Grievance Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
