# Generated by Django 5.2.10 on 2026-03-13 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0014_grievance_is_payment_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Unique code for the subcategory', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display subcategories')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='grievance.grievancecategory')),
            ],
            options={
                'verbose_name': 'Grievance SubCategory',
                'verbose_name_plural': 'Grievance SubCategories',
                'ordering': ['category__display_order', 'display_order', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.AddField(
            model_name='grievance',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory of the grievance (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grievances', to='grievance.grievancesubcategory'),
        ),
    ]
