# Generated by Django 5.2.10 on 2026-03-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0015_grievancesubcategory_grievance_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievancesubcategory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Price for grievance submission in this subcategory', max_digits=10),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Payment amount for grievance submission (from subcategory or default)', max_digits=10),
        ),
    ]
