# Generated by Django 6.0.1 on 2026-01-21 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('colleges', '0006_remove_college_admin_user_college_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('university_admin', 'University Admin'), ('college_admin', 'College Admin'), ('college_staff', 'College Staff'), ('student', 'Student'), ('examiner', 'Examiner')], default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='CollegeUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('admin', 'Administrator'), ('data_entry', 'Data Entry Operator'), ('verifier', 'Verifier'), ('approver', 'Approver'), ('accountant', 'Accountant'), ('clerk', 'Clerk')], default='clerk', max_length=50)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('can_manage_students', models.BooleanField(default=False)),
                ('can_manage_marks', models.BooleanField(default=False)),
                ('can_manage_results', models.BooleanField(default=False)),
                ('can_verify_data', models.BooleanField(default=False)),
                ('can_approve_certificates', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='colleges.college')),
                ('user', models.OneToOneField(limit_choices_to={'user_type__in': ['college_admin', 'college_staff']}, on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'College User Profile',
                'verbose_name_plural': 'College User Profiles',
                'unique_together': {('user', 'college')},
            },
        ),
    ]
