# Generated by Django 5.1.7 on 2026-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="type",
            field=models.CharField(default="student", max_length=20),
        ),
    ]
