# Generated by Django 6.0.1 on 2026-01-21 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_phone_alter_useraccount_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeuserprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'college_user'}, on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('university_admin', 'University Admin'), ('college_user', 'College User'), ('student', 'Student'), ('examiner', 'Examiner')], default='student', max_length=20),
        ),
    ]
