# Generated by Django 6.0.1 on 2026-01-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_historicalproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='type',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('college', 'College'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
