# Generated by Django 5.2.10 on 2026-01-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_useraccount_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collegeuserprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collegeuserprofile',
            name='role',
        ),
    ]
