# Generated by Django 5.2.10 on 2026-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_collegeuserprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='hindi_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hindi name'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address'),
        ),
    ]
