# Generated by Django 5.2.10 on 2026-01-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_hindi_name_alter_useraccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='hindi_name',
        ),
    ]
