# Generated by Django 5.2.10 on 2026-02-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_useraccount_hindi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_profile',
            field=models.CharField(blank=True, choices=[('mca_sem', 'MCA Semester'), ('plw', 'Pre-Law'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate')], max_length=20, null=True),
        ),
    ]
