# Generated by Django 5.2.10 on 2026-02-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useraccount_current_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_profile',
            field=models.CharField(blank=True, choices=[('mca_sem', 'MCA Semester'), ('plw', 'Pre-Law'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('btech', 'B.Tech'), ('mba', 'MBA')], max_length=20, null=True),
        ),
    ]
