# Generated by Django 5.2.10 on 2026-02-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_useraccount_current_profile'),
        ('colleges', '0009_college_center_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
    ]
