# Generated by Django 5.2.10 on 2026-02-09 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_useraccount_college'),
        ('pg', '0025_pgstudentcourseassessment_is_cia_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeuserprofile',
            name='PG_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_department_users', to='pg.pgdepartment'),
        ),
    ]
