# Generated by Django 5.2.10 on 2026-02-12 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_collegeuserprofile_pg_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('can_manage_voc_registration', models.BooleanField(default=False)),
                ('can_manage_grievances', models.BooleanField(default=False)),
                ('can_manage_ug', models.BooleanField(default=False)),
                ('can_manage_pg', models.BooleanField(default=False)),
                ('can_manage_mca', models.BooleanField(default=False)),
                ('can_manage_btech', models.BooleanField(default=False)),
                ('can_manage_colleges', models.BooleanField(default=False)),
                ('can_manage_university_settings', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'university_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='university_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University User Profile',
                'verbose_name_plural': 'University User Profiles',
            },
        ),
    ]
