# Generated by Django 5.2.11 on 2026-02-14 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_universityuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_password_changed',
            field=models.BooleanField(default=False, help_text='True if password has been changed by user/admin'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password_changed_by',
            field=models.ForeignKey(blank=True, help_text='User who last changed the password', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
