# Generated by Django 5.2.11 on 2026-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_useraccount_is_password_changed_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colleges', '0009_college_center_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user_type'], name='idx_user_type'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['username', 'user_type'], name='idx_username_type'),
        ),
    ]
