# Generated by Django 5.2.10 on 2026-02-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_useraccount_current_profile'),
        ('accounts', '0014_add_user_indexes'),
    ]

    operations = [
    ]
