# Generated by Django 5.2.10 on 2026-03-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20260216_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_profile',
            field=models.CharField(blank=True, choices=[('mca_sem', 'MCA Semester'), ('plw', 'Pre-Law'), ('llb', 'LLB'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate'), ('btech', 'B.Tech'), ('mba', 'MBA'), ('ug_before_cbcs', 'UG Old (Non-CBCS)')], max_length=20, null=True),
        ),
    ]
