# Generated by Django 6.0.1 on 2026-01-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('students', '0003_remove_student_enrollment_no_alter_student_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='college',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='program',
            name='college',
        ),
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
