# Generated by Django 6.0.1 on 2026-01-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_course_options_alter_course_unique_together_and_more'),
        ('colleges', '0004_alter_college_university'),
        ('students', '0004_alter_student_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
