# Generated by Django 6.0.1 on 2026-01-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_delete_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='college',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
