# Generated by Django 5.2.10 on 2026-01-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_professor_department_alter_course_department_and_more'),
        ('colleges', '0006_remove_college_admin_user_college_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='degree_offered',
            field=models.ManyToManyField(blank=True, related_name='colleges', to='academics.degree'),
        ),
    ]
