# Generated by Django 5.2.10 on 2026-02-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_college_degree_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_name_hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='college_name_krutidev',
            field=models.TextField(blank=True, null=True),
        ),
    ]
