# Generated by Django 5.2.10 on 2026-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_college_college_name_hindi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='center_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
