# Generated by Django 5.2.10 on 2026-02-02 14:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_college_college_name_hindi_and_more'),
        ('mca_sem', '0003_remove_mcaresultdetail_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCACommonCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('semester', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=50)),
                ('ltp', models.CharField(blank=True, max_length=20, null=True)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCA Common Course Structure',
                'verbose_name_plural': 'MCA Common Course Structures',
                'ordering': ['semester', 'course_name'],
            },
        ),
        migrations.CreateModel(
            name='MCACourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_name', models.CharField(blank=True, max_length=500, null=True)),
                ('course_short_name', models.CharField(blank=True, max_length=250, null=True)),
                ('course_type', models.CharField(blank=True, max_length=20, null=True)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=20, null=True)),
                ('max_credit', models.IntegerField(blank=True, null=True)),
                ('max_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCA Course Structure',
                'verbose_name_plural': 'MCA Course Structures',
            },
        ),
        migrations.CreateModel(
            name='MCAExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('semester', models.CharField(db_index=True, max_length=10)),
                ('session', models.CharField(db_index=True, max_length=10)),
                ('cia_pass', models.BooleanField(blank=True, null=True)),
                ('ese_pass', models.BooleanField(blank=True, null=True)),
                ('semester_result', models.CharField(choices=[('PASS', 'Pass'), ('PROMOTED', 'Promoted'), ('FAIL', 'Fail'), ('ABSENT', 'Absent'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('PARTLY_QUALIFIED', 'Partly Qualified')], db_index=True, max_length=20)),
                ('semester_max_credit', models.PositiveIntegerField(blank=True, null=True)),
                ('semester_credit_earned', models.PositiveIntegerField(blank=True, null=True)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('next_semester', models.PositiveIntegerField(blank=True, null=True)),
                ('next_sem_status', models.CharField(blank=True, choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible')], max_length=15, null=True)),
                ('is_legacy', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCA Exam Result',
                'verbose_name_plural': 'MCA Exam Results',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mcasemesterresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mcasemesterresult',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='mcabatch',
            options={'ordering': ['name'], 'verbose_name': 'MCA Batch', 'verbose_name_plural': 'MCA Batches'},
        ),
        migrations.AlterModelOptions(
            name='mcastudentassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'MCA Student Assessment', 'verbose_name_plural': 'MCA Student Assessments'},
        ),
        migrations.AlterModelOptions(
            name='mcastudentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'MCA Student Profile', 'verbose_name_plural': 'MCA Student Profiles'},
        ),
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_stud_sem_label',
        ),
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_college_sem',
        ),
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_subj_sem',
        ),
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_sem_label',
        ),
        migrations.RenameIndex(
            model_name='mcastudentassessment',
            new_name='idx_mca_stud_sem',
            old_name='idx_mca_student_sem',
        ),
        migrations.RemoveField(
            model_name='mcabatch',
            name='admission_year',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='college',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='comb_final_marks_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='comb_grace_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_grace_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_pass_marks',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='sem_grace_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='temp_total_gp',
        ),
        migrations.AddField(
            model_name='mcabatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcabatch',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcabatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mcastudentassessment',
            name='course_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentassessment',
            name='course_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentassessment',
            name='course_type',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentassessment',
            name='paper_code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='current_semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='hindi_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mca_students/profiles/'),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='session_str',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='mca_students/signatures/'),
        ),
        migrations.AddField(
            model_name='mcastudentprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Alumni', 'Alumni')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcabatch',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Batch name e.g., 2022-2024', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='session',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mcaexamschedule',
            name='exam_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcaexamschedule',
            name='sitting',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='exam_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='session',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcasemesterregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='attendance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='college_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_letter_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_max_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_numeric_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='comb_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_max_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('BACK', 'Back'), ('IMPROVEMENT', 'Improvement')], db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_is_absent',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_is_pass',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_max_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='ind_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='label',
            field=models.CharField(choices=[('CIA-Theory', 'CIA Theory'), ('CIA-Practical', 'CIA Practical'), ('ESE-Theory', 'ESE Theory'), ('ESE-Practical', 'ESE Practical')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='next_sem_status',
            field=models.CharField(blank=True, choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='sem_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='sem_max_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='sem_result',
            field=models.CharField(blank=True, choices=[('PASS', 'Pass'), ('PROMOTED', 'Promoted'), ('FAIL', 'Fail'), ('ABSENT', 'Absent'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('PARTLY_QUALIFIED', 'Partly Qualified')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='semester',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='session',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='sgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to='mca_sem.mcastudentprofile'),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mca_students', to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='registration_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mca_student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mcastudentassessment',
            index=models.Index(fields=['paper_code', 'semester'], name='idx_mca_paper_sem'),
        ),
        migrations.AddField(
            model_name='mcacoursestructure',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='mca_sem.mcabatch'),
        ),
        migrations.AddField(
            model_name='mcaexamresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='mca_sem.mcastudentprofile'),
        ),
        migrations.DeleteModel(
            name='MCASemesterResult',
        ),
        migrations.AddIndex(
            model_name='mcaexamresult',
            index=models.Index(fields=['student', 'semester'], name='mca_sem_mca_student_3a9297_idx'),
        ),
        migrations.AddIndex(
            model_name='mcaexamresult',
            index=models.Index(fields=['semester_result'], name='mca_sem_mca_semeste_647f4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mcaexamresult',
            unique_together={('student', 'semester', 'session')},
        ),
    ]
