# Generated by Django 5.2.10 on 2026-02-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0005_remove_mcastudentassessment_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcacoursestructure',
            name='batch',
        ),
    ]
