# Generated by Django 5.2.10 on 2026-02-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0006_remove_mcacoursestructure_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcacommoncoursestructure',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='mcacoursestructure',
            name='max_credit',
        ),
        migrations.RemoveField(
            model_name='mcaexamresult',
            name='semester_credit_earned',
        ),
        migrations.RemoveField(
            model_name='mcaexamresult',
            name='semester_max_credit',
        ),
        migrations.RemoveField(
            model_name='mcaexamresult',
            name='sgpa',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='comb_credit_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='comb_max_credits',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_credit_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_grade_point',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_max_credits',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='sem_credit_obtained',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='sem_max_credit',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='sgpa',
        ),
        migrations.AddField(
            model_name='mcaexamresult',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mcaexamresult',
            name='total_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mcacoursestructure',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mcacoursestructure',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=50, null=True),
        ),
    ]
