# Generated by Django 5.2.10 on 2026-02-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0007_remove_mcacommoncoursestructure_credit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_paper_sem',
        ),
        migrations.RemoveField(
            model_name='mcacoursestructure',
            name='paper_code',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='paper_code',
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='course_code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='mcastudentassessment',
            index=models.Index(fields=['course_code', 'semester'], name='idx_mca_course_sem'),
        ),
    ]
