# Generated by Django 5.2.10 on 2026-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0008_remove_mcastudentassessment_idx_mca_paper_sem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcaexamschedule',
            name='course_structure',
        ),
        migrations.AddField(
            model_name='mcaexamschedule',
            name='common_course_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='mca_sem.mcacommoncoursestructure'),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='label',
            field=models.CharField(choices=[('CIA', 'CIA'), ('ESE', 'ESE')], db_index=True, max_length=200),
        ),
    ]
