# Generated by Django 5.2.10 on 2026-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0009_remove_mcaexamschedule_course_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaexam',
            name='exam_center',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
