# Generated by Django 5.2.10 on 2026-02-03 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_college_college_name_hindi_and_more'),
        ('mca_sem', '0010_mcaexam_exam_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCAExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mcaexam',
            name='exam_center',
        ),
        migrations.AddField(
            model_name='mcaexam',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MCAExamCenterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_colleges', models.ManyToManyField(related_name='mca_exam_centers', to='colleges.college')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mappings', to='mca_sem.mcaexamcenter')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_mappings', to='mca_sem.mcaexam')),
            ],
            options={
                'verbose_name': 'MCA Exam Center Mapping',
                'verbose_name_plural': 'MCA Exam Center Mappings',
                'unique_together': {('exam', 'center')},
            },
        ),
    ]
