# Generated by Django 5.2.10 on 2026-02-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_college_college_name_hindi_and_more'),
        ('mca_sem', '0011_mcaexamcenter_remove_mcaexam_exam_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcaexamcentermapping',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mca_as_center_mappings', to='colleges.college'),
        ),
        migrations.DeleteModel(
            name='MCAExamCenter',
        ),
    ]
