# Generated by Django 5.2.10 on 2026-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0012_alter_mcaexamcentermapping_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SUSPENDED', 'Suspended'), ('ALUMNI', 'Alumni')], default='REGULAR', max_length=20),
        ),
    ]
