# Generated by Django 5.2.10 on 2026-02-06 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0012_alter_mcaexamcentermapping_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaexamregistration',
            name='backlog_subjects',
            field=models.ManyToManyField(blank=True, related_name='backlog_registrations', to='mca_sem.mcacommoncoursestructure'),
        ),
        migrations.AddField(
            model_name='mcaexamregistration',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='mca_sem.mcaexam'),
        ),
        migrations.AddField(
            model_name='mcaexamregistration',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('BACK', 'Back'), ('IMPROVEMENT', 'Improvement')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SUSPENDED', 'Suspended'), ('ALUMNI', 'Alumni')], default='REGULAR', max_length=20),
        ),
    ]
