# Generated by Django 5.2.10 on 2026-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0013_mcaexamregistration_backlog_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcaexamregistration',
            name='backlog_subjects',
        ),
        migrations.AddField(
            model_name='mcaexamregistration',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='registered_subjects', to='mca_sem.mcacommoncoursestructure'),
        ),
    ]
