# Generated by Django 5.2.10 on 2026-02-07 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0013_alter_mcastudentprofile_status'),
        ('mca_sem', '0014_remove_mcaexamregistration_backlog_subjects_and_more'),
    ]

    operations = [
    ]
