# Generated by Django 5.2.10 on 2026-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0015_merge_20260207_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='label',
            field=models.CharField(choices=[('CIA', 'CIA'), ('ESE', 'ESE'), ('Practical', 'Practical')], db_index=True, max_length=200),
        ),
    ]
