# Generated by Django 5.2.10 on 2026-02-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0016_alter_mcastudentassessment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcaexam',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mca_sem.mcabatch'),
        ),
        migrations.AlterField(
            model_name='mcastudentassessment',
            name='label',
            field=models.CharField(choices=[('CIA', 'CIA'), ('ESE', 'ESE')], db_index=True, max_length=200),
        ),
    ]
