# Generated by Django 5.2.10 on 2026-02-20 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0017_mcaexam_batch_alter_mcastudentassessment_label'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_stud_sem',
        ),
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_batch_sem',
        ),
        migrations.RemoveIndex(
            model_name='mcastudentassessment',
            name='idx_mca_course_sem',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='mcastudentassessment',
            name='semester',
        ),
        migrations.AddField(
            model_name='mcastudentassessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_course', to='mca_sem.mcacourse'),
        ),
        migrations.AddField(
            model_name='mcastudentassessment',
            name='course_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_course_structure', to='mca_sem.mcacoursestructure'),
        ),
        migrations.AddIndex(
            model_name='mcastudentassessment',
            index=models.Index(fields=['student', 'course_structure'], name='idx_mca_stud_struct'),
        ),
        migrations.AddIndex(
            model_name='mcastudentassessment',
            index=models.Index(fields=['batch', 'course_structure'], name='idx_mca_batch_struct'),
        ),
    ]
