# Generated by Django 5.2.10 on 2026-02-20 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0018_remove_mcastudentassessment_idx_mca_stud_sem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentassessment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_exam', to='mca_sem.mcaexam'),
        ),
    ]
