# Generated by Django 5.2.10 on 2026-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0019_mcastudentassessment_exam'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mcastudentassessment',
            index=models.Index(fields=['exam'], name='idx_mca_exam'),
        ),
    ]
