# Generated by Django 5.2.10 on 2026-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0020_mcastudentassessment_idx_mca_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcacommoncoursestructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mcacoursestructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
