# Generated by Django 5.2.10 on 2026-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0021_mcacommoncoursestructure_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcastudentassessment',
            name='semester',
            field=models.CharField(blank=True, db_index=True, help_text="Semester of the assessment, e.g., '1', '2'", max_length=20, null=True),
        ),
    ]
