# Generated by Django 5.2.12 on 2026-03-31 18:53

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca_sem', '0023_alter_mcastudentprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('mca_students/profiles/')),
        ),
        migrations.AlterField(
            model_name='mcastudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('mca_students/signatures/')),
        ),
    ]
