# Generated by Django 5.2.10 on 2026-03-11 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0009_college_center_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLBBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLBCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('duration_years', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLBCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_marks', models.PositiveIntegerField(default=100)),
                ('pass_marks', models.PositiveIntegerField(default=33)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLBSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLBExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('semester', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_month_year', models.CharField(max_length=20)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llb.llbbatch')),
            ],
        ),
        migrations.CreateModel(
            name='LLBExamCenterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_colleges', models.ManyToManyField(related_name='llb_exam_centers', to='colleges.college')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llb_as_center_mappings', to='colleges.college')),
                ('exams', models.ManyToManyField(related_name='center_mappings', to='llb.llbexam')),
            ],
        ),
        migrations.CreateModel(
            name='LLBExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(blank=True, max_length=100, null=True)),
                ('sitting', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='llb.llbexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='llb.llbcoursestructure')),
            ],
        ),
        migrations.CreateModel(
            name='LLBStudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_center', models.CharField(blank=True, max_length=255, null=True)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('grace', models.PositiveIntegerField(blank=True, null=True)),
                ('result_status', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='llb.llbexam')),
            ],
        ),
        migrations.CreateModel(
            name='LLBStudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paper_code', models.CharField(blank=True, max_length=10, null=True)),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('total_secured_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('total_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_result', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='llb.llbcoursestructure')),
                ('exam_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='llb.llbstudentexamresult')),
            ],
        ),
        migrations.CreateModel(
            name='LLBStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hindi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('category', models.CharField(blank=True, choices=[('General', 'General'), ('EWS', 'EWS'), ('OBC', 'OBC'), ('BC', 'BC'), ('BC-I', 'BC-I'), ('BC-II', 'BC-II'), ('BC (Annexure-II)', 'BC (Annexure-II)'), ('SC', 'SC'), ('ST', 'ST'), ('EBC', 'EBC'), ('EBC-I', 'EBC-I'), ('EBC (Annexure-I)', 'EBC (Annexure-I)')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='llb/profiles/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='llb/signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llb.llbbatch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='llb_students', to='colleges.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llb.llbcourse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llb_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='llbstudentexamresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='llb.llbstudentprofile'),
        ),
        migrations.CreateModel(
            name='LLBExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_type', models.CharField(default='REGULAR', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='llb.llbexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='llb.llbstudentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LLBYearRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('exam_eligible', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_registrations', to='llb.llbstudentprofile')),
            ],
        ),
    ]
