# Generated by Django 5.2.10 on 2026-03-11 11:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLBStudentCourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_name', models.CharField(blank=True, help_text='Course Name', max_length=250, null=True)),
                ('course_short_name', models.CharField(blank=True, help_text='Course Short Name', max_length=250, null=True)),
                ('course_type', models.CharField(blank=True, db_index=True, help_text='Course Type', max_length=20, null=True)),
                ('course_code', models.CharField(blank=True, help_text='Course Code', max_length=20, null=True)),
                ('paper_code', models.CharField(blank=True, db_index=True, help_text='Paper Code', max_length=20, null=True)),
                ('semester', models.CharField(blank=True, db_index=True, help_text='Semester', max_length=20, null=True)),
                ('label', models.CharField(db_index=True, help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100)),
                ('session', models.CharField(blank=True, db_index=True, help_text='Session', max_length=10, null=True)),
                ('college_code', models.CharField(blank=True, help_text='College Code', max_length=10, null=True)),
                ('exam_type', models.CharField(blank=True, db_index=True, help_text='Type Regular/Back', max_length=10, null=True)),
                ('ind_max_marks', models.IntegerField(blank=True, help_text='Individual MAX MARKS', null=True)),
                ('ind_pass_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Individual PASS MARKS', max_digits=10, null=True)),
                ('ind_is_absent', models.BooleanField(db_index=True, default=False, help_text='Is Absent')),
                ('ind_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Individual MARKS OBTAINED', max_digits=10, null=True)),
                ('ind_grace_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Individual GRACE MARKS OBTAINED', max_digits=10, null=True)),
                ('ind_final_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Individual FINAL MARKS OBTAINED', max_digits=10, null=True)),
                ('ind_is_pass', models.BooleanField(blank=True, help_text='Is Pass', null=True)),
                ('comb_max_marks', models.IntegerField(blank=True, help_text='Total MAX MARKS', null=True)),
                ('comb_pass_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Total PASS MARKS', max_digits=10, null=True)),
                ('comb_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total MARKS OBTAINED', max_digits=10, null=True)),
                ('comb_grace_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total GRACE MARKS OBTAINED', max_digits=10, null=True)),
                ('comb_final_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total FINAL MARKS OBTAINED', max_digits=10, null=True)),
                ('comb_is_pass', models.BooleanField(blank=True, help_text='Is Pass', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llb.llbbatch')),
                ('exam_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='llb.llbstudentexamresult')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llb_student_course_assessment', to='llb.llbstudentprofile')),
            ],
        ),
    ]
