# Generated by Django 5.2.10 on 2026-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0002_llbstudentcourseassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=100, null=True),
        ),
    ]
