# Generated by Django 5.2.10 on 2026-03-11 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0003_alter_llbstudentcourseassessment_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Subject Name (e.g., Constitutional Law-I)', max_length=255)),
                ('course_code', models.CharField(help_text='Course Code', max_length=100)),
                ('paper_code', models.CharField(help_text='Paper Code', max_length=20)),
                ('full_marks', models.PositiveIntegerField(help_text='Total Full Marks (CIA + ESE)')),
                ('pass_marks', models.PositiveIntegerField(help_text='Total Pass Marks')),
                ('cia_max_marks', models.PositiveIntegerField(help_text='CIA Maximum Marks')),
                ('ese_max_marks', models.PositiveIntegerField(help_text='ESE Maximum Marks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='llbstudentassessment',
            name='exam_result',
        ),
        migrations.RemoveField(
            model_name='llbstudentassessment',
            name='subject',
        ),
        migrations.AlterModelOptions(
            name='llbstudentcourseassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'LLB Student Assessment', 'verbose_name_plural': 'LLB Student Assessments'},
        ),
        migrations.RemoveField(
            model_name='llbstudentcourseassessment',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='llbstudentcourseassessment',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='llbstudentcourseassessment',
            name='course_short_name',
        ),
        migrations.RemoveField(
            model_name='llbstudentcourseassessment',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='llbstudentcourseassessment',
            name='paper_code',
        ),
        migrations.RemoveField(
            model_name='llbstudentexamresult',
            name='exam_center',
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_course', to='llb.llbcourse'),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='course_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course Final MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='course_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course Total MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='course_max_marks',
            field=models.IntegerField(blank=True, help_text='Course Total MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='course_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_course_structure', to='llb.llbcoursestructure'),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_exam', to='llb.llbexam'),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='subject_result',
            field=models.CharField(blank=True, help_text='Subject Result (PASS/FAIL)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='llbexam',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester Code from staging', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='llb.llbbatch'),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='comb_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='comb_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='comb_is_pass',
            field=models.BooleanField(blank=True, help_text='Combined Is Pass', null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='comb_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='comb_max_marks',
            field=models.IntegerField(blank=True, help_text='Combined MAX MARKS', null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='comb_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='exam_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments_result', to='llb.llbstudentexamresult'),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='label',
            field=models.CharField(db_index=True, help_text='Assessment label (e.g., CIA, ESE, CIA-Theory)', max_length=200),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='semester',
            field=models.CharField(blank=True, db_index=True, help_text="Semester of the assessment, e.g., '1', '2'", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='llbstudentcourseassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to='llb.llbstudentprofile'),
        ),
        migrations.AddIndex(
            model_name='llbstudentcourseassessment',
            index=models.Index(fields=['student', 'course_structure'], name='idx_llb_stud_struct'),
        ),
        migrations.AddIndex(
            model_name='llbstudentcourseassessment',
            index=models.Index(fields=['batch', 'course_structure'], name='idx_llb_batch_struct'),
        ),
        migrations.AddIndex(
            model_name='llbstudentcourseassessment',
            index=models.Index(fields=['exam'], name='idx_llb_exam'),
        ),
        migrations.DeleteModel(
            name='LLBStudentAssessment',
        ),
    ]
