# Generated by Django 5.2.10 on 2026-03-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0004_commoncoursestructure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncoursestructure',
            name='paper_code',
        ),
        migrations.AddField(
            model_name='llbstudentcourseassessment',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code for this assessment', max_length=20, null=True),
        ),
    ]
