# Generated by Django 5.2.10 on 2026-03-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0005_remove_commoncoursestructure_paper_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncoursestructure',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester Code from staging', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='llbcoursestructure',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester Code from staging', max_length=20, null=True),
        ),
    ]
