# Generated by Django 5.2.10 on 2026-03-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0006_commoncoursestructure_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llbcoursestructure',
            name='status',
            field=models.CharField(blank=True, help_text='Assessment type: CIA or ESE', max_length=200, null=True),
        ),
    ]
