# Generated by Django 5.2.10 on 2026-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0007_llbcoursestructure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncoursestructure',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='llbcoursestructure',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='llbcoursestructure',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commoncoursestructure',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=100, null=True),
        ),
    ]
