# Generated by Django 5.2.10 on 2026-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0008_commoncoursestructure_paper_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncoursestructure',
            name='subject_code',
            field=models.CharField(blank=True, help_text='Subject Code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='llbcoursestructure',
            name='subject_code',
            field=models.CharField(blank=True, help_text='Subject Code', max_length=100, null=True),
        ),
    ]
