# Generated by Django 5.2.10 on 2026-03-24 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llb', '0011_change_ind_marks_obtained_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLBStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.JSONField(blank=True, help_text='The statistics JSON structure', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLB Statistics',
                'verbose_name_plural': 'LLB Statistics',
            },
        ),
    ]
