# Generated by Django 5.2.10 on 2026-02-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbacoursestructure',
            name='credit',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
