# Generated by Django 5.2.10 on 2026-02-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0002_mbacoursestructure_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbacourse',
            name='discipline_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
