# Generated by Django 5.2.10 on 2026-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0003_mbacourse_discipline_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbastudentprofile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Alumni', 'Alumni')], default='Regular', max_length=20),
        ),
    ]
