# Generated by Django 5.2.10 on 2026-02-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0005_alter_mbastudentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbaexamregistration',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mba_sem.mbaexam'),
        ),
        migrations.AddField(
            model_name='mbaexamregistration',
            name='exam_subjects',
            field=models.ManyToManyField(blank=True, to='mba_sem.mbacommoncoursestructure'),
        ),
        migrations.AddField(
            model_name='mbaexamregistration',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('BACK', 'Back'), ('IMPROVEMENT', 'Improvement')], default='REGULAR', max_length=20),
        ),
    ]
