# Generated by Django 5.2.11 on 2026-02-17 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0006_mbaexamregistration_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_name', models.CharField(blank=True, help_text='Course Name', max_length=250, null=True)),
                ('course_short_name', models.CharField(blank=True, help_text="Course Short Name (e.g., 'IM' for 'Introductory Microeconomics').", max_length=250, null=True)),
                ('course_type', models.CharField(blank=True, db_index=True, help_text='Course Type', max_length=20, null=True)),
                ('course_code', models.CharField(blank=True, help_text='Course Code', max_length=20, null=True)),
                ('paper_code', models.CharField(blank=True, db_index=True, help_text='Paper Code', max_length=20, null=True)),
                ('semester', models.CharField(blank=True, db_index=True, help_text='Semester', max_length=20, null=True)),
                ('label', models.CharField(db_index=True, help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100)),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
                ('session', models.CharField(blank=True, db_index=True, help_text='Session', max_length=10, null=True)),
                ('college_code', models.CharField(blank=True, help_text='College Code', max_length=10, null=True)),
                ('exam_type', models.CharField(blank=True, db_index=True, help_text='Type Regular/Back', max_length=10, null=True)),
                ('attendance', models.CharField(blank=True, help_text='Attendance', max_length=10, null=True)),
                ('ind_max_marks', models.IntegerField(blank=True, help_text='Individual MAX MARKS', null=True)),
                ('ind_pass_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Individual PASS MARKS', max_digits=10, null=True)),
                ('ind_is_absent', models.BooleanField(db_index=True, default=True, help_text='Is Absent')),
                ('ind_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Individual MARKS OBTAINED', max_digits=10, null=True)),
                ('ind_grace_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Individual GRACE MARKS OBTAINED', max_digits=10, null=True)),
                ('ind_final_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Individual FINAL MARKS OBTAINED', max_digits=10, null=True)),
                ('ind_is_pass', models.BooleanField(blank=True, help_text='Is Pass', null=True)),
                ('comb_max_marks', models.IntegerField(blank=True, help_text='Total MAX MARKS', null=True)),
                ('comb_max_credits', models.IntegerField(blank=True, help_text='Total MAX CREDIT', null=True)),
                ('comb_pass_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Total PASS MARKS', max_digits=10, null=True)),
                ('comb_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total MARKS OBTAINED', max_digits=10, null=True)),
                ('comb_grace_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total GRACE MARKS OBTAINED', max_digits=10, null=True)),
                ('comb_final_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total FINAL MARKS OBTAINED', max_digits=10, null=True)),
                ('comb_credit_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Total CREDIT OBTAINED', max_digits=10, null=True)),
                ('comb_numeric_grade', models.DecimalField(blank=True, decimal_places=2, help_text='Total NUMERIC GRADE', max_digits=10, null=True)),
                ('comb_letter_grade', models.CharField(blank=True, help_text='Total LETTER GRADE', max_length=10, null=True)),
                ('comb_grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='Total GRADE POINT', max_digits=10, null=True)),
                ('course_max_marks', models.IntegerField(blank=True, help_text='Course MAX MARKS', null=True)),
                ('course_max_credits', models.IntegerField(blank=True, help_text='Course MAX CREDIT', null=True)),
                ('course_pass_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Course PASS MARKS', max_digits=10, null=True)),
                ('course_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Course MARKS OBTAINED', max_digits=10, null=True)),
                ('course_grace_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Course GRACE MARKS', max_digits=10, null=True)),
                ('course_final_marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Course FINAL MARKS OBTAINED', max_digits=10, null=True)),
                ('course_credit_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Course CREDIT OBTAINED', max_digits=10, null=True)),
                ('course_grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='Course GRADE POINT', max_digits=10, null=True)),
                ('sem_max_credit', models.IntegerField(blank=True, help_text='Semester MAX CREDIT', null=True)),
                ('sem_credit_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Semester CREDIT OBTAINED', max_digits=10, null=True)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Semester GRADE POINT', max_digits=10, null=True)),
                ('sem_result', models.CharField(blank=True, help_text='Semester Result eg: pass/fail/promoted', max_length=10, null=True)),
                ('next_sem_status', models.CharField(blank=True, help_text='Next Semester Status eg: eligible/not eligible', max_length=10, null=True)),
                ('sem_grace_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Semester GRACE MARKS OBTAINED', max_digits=10, null=True)),
                ('temp_total_gp', models.DecimalField(blank=True, decimal_places=2, help_text='Total GRADE POINT', max_digits=10, null=True)),
                ('json_data', models.JSONField(blank=True, help_text='JSON Data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mba_sem.mbabatch')),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, to='mba_sem.mbastudentprofile')),
            ],
            options={
                'verbose_name': 'Student Course Assessment',
                'verbose_name_plural': 'Student Course Assessments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'semester'], name='mba_idx_student_sem'), models.Index(fields=['student', 'semester', 'label'], name='mba_idx_stud_sem_label'), models.Index(fields=['batch', 'semester'], name='mba_idx_batch_sem'), models.Index(fields=['paper_code', 'semester'], name='mba_idx_paper_sem'), models.Index(fields=['semester', 'label'], name='mba_idx_sem_label'), models.Index(fields=['student', 'semester', 'session', 'paper_code', 'label', 'exam_type'], name='mba_idx_reg_dup_check')],
            },
        ),
    ]
