# Generated by Django 5.2.11 on 2026-02-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0007_studentcourseassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='mba_student_course_assessment', to='mba_sem.mbastudentprofile'),
        ),
    ]
