# Generated by Django 5.2.11 on 2026-02-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0008_alter_studentcourseassessment_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCourseAssessment',
            new_name='MBAStudentCourseAssessment',
        ),
    ]
