# Generated by Django 5.2.11 on 2026-02-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0009_rename_studentcourseassessment_mbastudentcourseassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbastudentcourseassessment',
            name='mba_exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mba_sem.mbaexam'),
        ),
    ]
