# Generated by Django 5.2.11 on 2026-02-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0010_mbastudentcourseassessment_mba_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mbastudentcourseassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'MBA Student Course Assessment', 'verbose_name_plural': 'Student Course Assessments'},
        ),
    ]
