# Generated by Django 5.2.11 on 2026-02-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0012_alter_mbastudentcourseassessment_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mbastudentcourseassessment',
            unique_together={('student', 'paper_code', 'semester', 'label', 'exam_type', 'session')},
        ),
    ]
