# Generated by Django 5.2.11 on 2026-02-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0013_alter_mbastudentcourseassessment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbastudentcourseassessment',
            name='ind_is_absent',
            field=models.BooleanField(db_index=True, default=False, help_text='Is Absent'),
        ),
    ]
