# Generated by Django 5.2.11 on 2026-02-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sem', '0014_alter_mbastudentcourseassessment_ind_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_1_credit_earned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_1_gpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_2_credit_earned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_2_gpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_3_credit_earned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_3_gpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_4_credit_earned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mbastudentprofile',
            name='sem_4_gpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
