# Generated by Django 5.2.11 on 2026-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bca_hons_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcahonscommoncoursestructure',
            name='paper_type',
            field=models.CharField(blank=True, help_text='Honours/Subsidiary/Composition', max_length=20, null=True),
        ),
    ]
