# Generated by Django 5.2.10 on 2026-01-23 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_student_department'),
        ('university', '0002_faculty_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Course Name', max_length=100, null=True)),
                ('course_type', models.CharField(blank=True, help_text='Course Type', max_length=20, null=True)),
                ('code', models.CharField(blank=True, help_text='Course Code', max_length=20, null=True)),
                ('max_credit', models.IntegerField(blank=True, help_text='Course Credit', null=True)),
                ('max_marks', models.IntegerField(blank=True, help_text='Course Marks', null=True)),
                ('min_mark', models.IntegerField(blank=True, help_text='Pass Mark', null=True)),
                ('min_credit', models.IntegerField(blank=True, help_text='Min Credit', null=True)),
                ('description', models.TextField(blank=True, help_text='Course Description', null=True)),
                ('label', models.CharField(help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100)),
                ('semester', models.IntegerField(blank=True, help_text='Semester', null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_course_structures', to='university.department')),
            ],
            options={
                'verbose_name': 'Course Structure',
                'verbose_name_plural': 'Course Structures',
            },
        ),
        migrations.CreateModel(
            name='PGExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Start Date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='End Date', null=True)),
                ('is_open', models.BooleanField(default=False, help_text='Is Open')),
                ('fees', models.IntegerField(blank=True, help_text='Fees', null=True)),
                ('sem', models.IntegerField(blank=True, help_text='Semester', null=True)),
                ('status', models.CharField(blank=True, help_text='Status', max_length=10, null=True)),
                ('session', models.CharField(blank=True, help_text='Session', max_length=10, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_exam_registrations', to='students.student')),
            ],
            options={
                'verbose_name': 'Exam Registration',
                'verbose_name_plural': 'Exam Registrations',
            },
        ),
        migrations.CreateModel(
            name='PGSemesterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Start Date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='End Date', null=True)),
                ('is_open', models.BooleanField(default=False, help_text='Is Open')),
                ('sem', models.IntegerField(blank=True, help_text='Semester', null=True)),
                ('status', models.CharField(blank=True, help_text='Status open/closed', max_length=10, null=True)),
                ('exam_eligible', models.BooleanField(default=False, help_text='Eligible for Exam')),
                ('remarks', models.TextField(blank=True, help_text='Remarks', null=True)),
                ('session', models.CharField(blank=True, help_text='Session', max_length=10, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_semester_registrations', to='students.student')),
            ],
            options={
                'verbose_name': 'Semester Registration',
                'verbose_name_plural': 'Semester Registrations',
            },
        ),
        migrations.CreateModel(
            name='PGStudentCourseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_type', models.CharField(blank=True, help_text='Course Type', max_length=20, null=True)),
                ('code', models.CharField(blank=True, help_text='Course Code', max_length=20, null=True)),
                ('semester', models.IntegerField(blank=True, help_text='Semester', null=True)),
                ('max_credit', models.IntegerField(blank=True, help_text='Course Credit', null=True)),
                ('max_marks', models.IntegerField(blank=True, help_text='Course Marks', null=True)),
                ('min_mark', models.IntegerField(blank=True, help_text='Min Mark', null=True)),
                ('min_credit', models.IntegerField(blank=True, help_text='Min Credit', null=True)),
                ('description', models.TextField(blank=True, help_text='Course Description', null=True)),
                ('label', models.CharField(help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100)),
                ('marks_obtained', models.IntegerField(blank=True, help_text='Marks Obtained', null=True)),
                ('credit_obtained', models.IntegerField(blank=True, help_text='Credit Obtained', null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade', max_length=10, null=True)),
                ('numeric_grade', models.IntegerField(blank=True, help_text='Numeric Grade', null=True)),
                ('is_absent', models.BooleanField(default=False, help_text='Is Absent')),
                ('exam_type', models.CharField(blank=True, help_text='Type Regular/Back', max_length=10, null=True)),
                ('session', models.CharField(blank=True, help_text='Session', max_length=10, null=True)),
                ('exam_result', models.CharField(blank=True, help_text='Status pass/fail/promoted', max_length=10, null=True)),
                ('batch', models.CharField(blank=True, help_text='Batch', max_length=10, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_course_assessments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Course Assessment',
                'verbose_name_plural': 'Student Course Assessments',
            },
        ),
    ]
