# Generated by Django 5.2.10 on 2026-01-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0001_initial'),
        ('students', '0006_student_degree_student_major_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgcoursestructure',
            options={'verbose_name': 'PG Course Structure', 'verbose_name_plural': 'PG Course Structures'},
        ),
        migrations.AlterModelOptions(
            name='pgexamregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'PG Exam Registration', 'verbose_name_plural': 'PG Exam Registrations'},
        ),
        migrations.AlterModelOptions(
            name='pgsemesterregistration',
            options={'verbose_name': 'PG Semester Registration', 'verbose_name_plural': 'PG Semester Registrations'},
        ),
        migrations.AlterModelOptions(
            name='pgstudentcourseassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'PG Student Course Assessment', 'verbose_name_plural': 'PG Student Course Assessments'},
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='name',
            field=models.CharField(blank=True, help_text='Course Name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='pgexamregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At'),
        ),
        migrations.AlterField(
            model_name='pgexamregistration',
            name='json_data',
            field=models.JSONField(blank=True, help_text='JSON Data', null=True),
        ),
        migrations.AlterField(
            model_name='pgexamregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated At'),
        ),
        migrations.AlterField(
            model_name='pgsemesterregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At'),
        ),
        migrations.AlterField(
            model_name='pgsemesterregistration',
            name='json_data',
            field=models.JSONField(blank=True, help_text='JSON Data', null=True),
        ),
        migrations.AlterField(
            model_name='pgsemesterregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated At'),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At'),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='json_data',
            field=models.JSONField(blank=True, help_text='JSON Data', null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='pg_course_assessments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated At'),
        ),
        migrations.AlterUniqueTogether(
            name='pgstudentcourseassessment',
            unique_together={('student', 'course_type', 'semester', 'label', 'exam_type')},
        ),
    ]
