# Generated by Django 5.2.10 on 2026-01-24 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_professor_department_alter_course_department_and_more'),
        ('colleges', '0007_college_degree_offered'),
        ('pg', '0002_alter_pgcoursestructure_options_and_more'),
        ('university', '0005_alter_department_code_alter_university_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hindi_name', models.CharField(blank=True, max_length=250, null=True)),
                ('registration_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('migration_submitted', models.BooleanField(default=False)),
                ('last_university', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('caste', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('roll_no', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_semester', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Alumni', 'Alumni')], default='Active', max_length=20)),
                ('cc_course', models.CharField(blank=True, help_text='Core Course (CC)', max_length=250, null=True)),
                ('sec_course', models.CharField(blank=True, help_text='Skill Enhancement Course (SEC)', max_length=250, null=True)),
                ('ec_course', models.CharField(blank=True, help_text='Elective Course (EC)', max_length=250, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='pg_students/profiles/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='pg_students/signatures/')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_students', to='colleges.college')),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_students', to='academics.degree')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_students', to='university.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_students', to='academics.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pg_student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PG Student Profile',
                'verbose_name_plural': 'PG Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pgexamregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='pg.pgstudentprofile'),
        ),
        migrations.AlterField(
            model_name='pgsemesterregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_registrations', to='pg.pgstudentprofile'),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='course_assessments', to='pg.pgstudentprofile'),
        ),
    ]
