# Generated by Django 5.2.10 on 2026-01-24 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_pgstudentprofile_alter_pgexamregistration_student_and_more'),
        ('university', '0005_alter_department_code_alter_university_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='e.g., M.A., M.Sc., M.Com., MBA, MCA', max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='e.g., MA, MSc', max_length=50, null=True)),
                ('total_semesters', models.PositiveIntegerField(default=4)),
                ('total_years', models.PositiveIntegerField(default=2)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PG Degree',
                'verbose_name_plural': 'PG Degrees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PGDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('head_of_department', models.CharField(blank=True, max_length=255, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PG Department',
                'verbose_name_plural': 'PG Departments',
            },
        ),
        migrations.AlterField(
            model_name='pgstudentprofile',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pg.pgdegree'),
        ),
        migrations.AlterField(
            model_name='pgcoursestructure',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='pg.pgdepartment'),
        ),
        migrations.AlterField(
            model_name='pgstudentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pg.pgdepartment'),
        ),
        migrations.CreateModel(
            name='PGFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_faculties', to='university.university')),
            ],
            options={
                'verbose_name': 'PG Faculty',
                'verbose_name_plural': 'PG Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pgdepartment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='pg.pgfaculty'),
        ),
        migrations.CreateModel(
            name='PGProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Program name e.g., M.A. History', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='e.g., MA History', max_length=50, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='pg.pgdegree')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='pg.pgdepartment')),
            ],
            options={
                'verbose_name': 'PG Program',
                'verbose_name_plural': 'PG Programs',
            },
        ),
        migrations.AlterField(
            model_name='pgstudentprofile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='pg.pgprogram'),
        ),
    ]
