# Generated by Django 5.2.10 on 2026-01-24 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_pgdegree_pgdepartment_alter_pgstudentprofile_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Batch name e.g., 2023-2025', max_length=255)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pg.pgprogram')),
            ],
            options={
                'verbose_name': 'PG Batch',
                'verbose_name_plural': 'PG Batches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pgcoursestructure',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='pg.pgbatch'),
        ),
    ]
