# Generated by Django 5.2.10 on 2026-01-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_alter_pgcoursestructure_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcoursestructure',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='attendance',
            field=models.CharField(blank=True, help_text='Attendance', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_student_assessments', to='pg.pgdepartment'),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pgcoursestructure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='pg.pgdepartment'),
        ),
        migrations.AlterField(
            model_name='pgcoursestructure',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_student_assessments', to='pg.pgbatch'),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester', max_length=20, null=True),
        ),
    ]
