# Generated by Django 5.2.10 on 2026-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0007_pgcoursestructure_paper_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgstudentprofile',
            name='enrollment_date',
        ),
        migrations.AlterField(
            model_name='pgstudentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
