# Generated by Django 5.2.10 on 2026-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0008_remove_pgstudentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentprofile',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
