# Generated by Django 5.2.10 on 2026-01-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0009_pgstudentprofile_apaar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
