# Generated by Django 5.2.10 on 2026-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0010_pgstudentprofile_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
