# Generated by Django 5.2.10 on 2026-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0011_pgstudentprofile_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pgstudentcourseassessment',
            old_name='code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='pgstudentcourseassessment',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AlterUniqueTogether(
            name='pgstudentcourseassessment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pgcoursestructure',
            name='min_credit',
        ),
        migrations.RemoveField(
            model_name='pgcoursestructure',
            name='min_mark',
        ),
        migrations.RemoveField(
            model_name='pgcoursestructure',
            name='name',
        ),
        migrations.AddField(
            model_name='pgcoursestructure',
            name='course_name',
            field=models.CharField(blank=True, help_text='Course Name', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pgcoursestructure',
            name='course_short_name',
            field=models.CharField(blank=True, help_text="Course Short Name (e.g., 'IM' for 'Introductory Microeconomics').", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pgcoursestructure',
            name='min_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pass Mark', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='college_code',
            field=models.CharField(blank=True, help_text='College Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total CREDIT OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_letter_grade',
            field=models.CharField(blank=True, help_text='Total LETTER GRADE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_max_credits',
            field=models.IntegerField(blank=True, help_text='Total MAX CREDIT', null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_max_marks',
            field=models.IntegerField(blank=True, help_text='Total MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_numeric_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total NUMERIC GRADE', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course CREDIT OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course GRACE MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course GRADE POINT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_max_credits',
            field=models.IntegerField(blank=True, help_text='Course MAX CREDIT', null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_max_marks',
            field=models.IntegerField(blank=True, help_text='Course MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='course_short_name',
            field=models.CharField(blank=True, help_text="Course Short Name (e.g., 'IM' for 'Introductory Microeconomics').", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_is_absent',
            field=models.BooleanField(db_index=True, default=True, help_text='Is Absent'),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_max_marks',
            field=models.IntegerField(blank=True, help_text='Individual MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='next_sem_status',
            field=models.CharField(blank=True, help_text='Next Semester Status eg: eligible/not eligible', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='sem_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester CREDIT OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='sem_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='sem_max_credit',
            field=models.IntegerField(blank=True, help_text='Semester MAX CREDIT', null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='sem_result',
            field=models.CharField(blank=True, help_text='Semester Result eg: pass/fail/promoted', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='sgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester GRADE POINT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='temp_total_gp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total GRADE POINT', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pgcoursestructure',
            name='max_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course Marks', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='course_type',
            field=models.CharField(blank=True, db_index=True, help_text='Course Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='exam_type',
            field=models.CharField(blank=True, db_index=True, help_text='Type Regular/Back', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='label',
            field=models.CharField(db_index=True, help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='paper_code',
            field=models.CharField(blank=True, db_index=True, help_text='Paper Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='semester',
            field=models.CharField(blank=True, db_index=True, help_text='Semester', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pgstudentcourseassessment',
            name='session',
            field=models.CharField(blank=True, db_index=True, help_text='Session', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['student', 'semester'], name='pg_idx_student_sem'),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['student', 'semester', 'label'], name='pg_idx_stud_sem_lbl'),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['department', 'semester'], name='pg_idx_dept_sem'),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['department', 'semester', 'label'], name='pg_idx_dept_sem_lbl'),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['batch', 'semester'], name='pg_idx_batch_sem'),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['paper_code', 'semester'], name='pg_idx_paper_sem'),
        ),
        migrations.AddIndex(
            model_name='pgstudentcourseassessment',
            index=models.Index(fields=['semester', 'label'], name='pg_idx_sem_label'),
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='credit_obtained',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='exam_result',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='is_absent',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='max_credit',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='min_credit',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='min_mark',
        ),
        migrations.RemoveField(
            model_name='pgstudentcourseassessment',
            name='numeric_grade',
        ),
    ]
