# Generated by Django 5.2.10 on 2026-01-27 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0012_rename_code_pgstudentcourseassessment_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('semester', models.CharField(help_text='e.g., Semester-I', max_length=50)),
                ('course_name', models.CharField(help_text='e.g., Major Course 1', max_length=255)),
                ('course_type', models.CharField(help_text='e.g., MJC-1', max_length=50)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=100)),
                ('code', models.CharField(blank=True, help_text='Course Code', max_length=20, null=True)),
                ('cia_marks', models.PositiveIntegerField(default=100)),
                ('ese_marks', models.PositiveIntegerField(default=100)),
                ('new_code', models.CharField(blank=True, help_text='Course Code', max_length=20, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Common Course Structure',
                'verbose_name_plural': 'Common Course Structures',
                'ordering': ['semester', 'course_name'],
            },
        ),
    ]
