# Generated by Django 5.2.10 on 2026-01-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0013_commoncoursestructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoncoursestructure',
            name='code',
        ),
        migrations.AddField(
            model_name='commoncoursestructure',
            name='old_code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=20, null=True),
        ),
    ]
