# Generated by Django 5.2.10 on 2026-01-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0014_add_common_course_structure_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonCourseStructure',
            new_name='PGCommonCourseStructure',
        ),
    ]
