# Generated by Django 5.2.10 on 2026-01-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0015_rename_commoncoursestructure_pgcommoncoursestructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgcommoncoursestructure',
            options={'ordering': ['semester', 'course_name'], 'verbose_name': 'PGCommon Course Structure', 'verbose_name_plural': 'Common Course Structures'},
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='course_name',
            field=models.CharField(help_text='e.g., CC ', max_length=255),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='course_type',
            field=models.CharField(help_text='e.g., CC-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='old_code',
            field=models.CharField(blank=True, help_text='eg: 1001, 1002, 2001', max_length=20, null=True),
        ),
    ]
