# Generated by Django 5.2.10 on 2026-01-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0016_add_subject_to_pg_common_course_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgdepartment',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='pg.pgfaculty'),
        ),
    ]
