# Generated by Django 5.2.10 on 2026-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0017_alter_pgdepartment_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcommoncoursestructure',
            name='course_code',
            field=models.CharField(blank=True, help_text='e.g., CC-1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='comb_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total GRADE POINT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='ind_is_pass',
            field=models.BooleanField(blank=True, help_text='Is Pass', null=True),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='cia_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='course_type',
            field=models.CharField(help_text='e.g., CC', max_length=50),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='ese_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='old_code',
            field=models.CharField(blank=True, help_text='eg: cc-', max_length=20, null=True),
        ),
    ]
