# Generated by Django 5.2.10 on 2026-02-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0018_pgcommoncoursestructure_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcommoncoursestructure',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments offering this common course', related_name='common_courses', to='pg.pgdepartment'),
        ),
    ]
