# Generated by Django 5.2.10 on 2026-02-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0019_pgcommoncoursestructure_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='course_name',
            field=models.CharField(blank=True, help_text='e.g., CC ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pgcommoncoursestructure',
            name='course_type',
            field=models.CharField(blank=True, help_text='e.g., CC', max_length=50, null=True),
        ),
    ]
