# Generated by Django 5.2.10 on 2026-02-02 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0020_alter_pgcommoncoursestructure_course_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('semester', models.CharField(db_index=True, max_length=10)),
                ('session', models.CharField(db_index=True, max_length=10)),
                ('cia_pass', models.BooleanField(blank=True, null=True)),
                ('ese_pass', models.BooleanField(blank=True, null=True)),
                ('semester_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('PROMOTED', 'Promoted'), ('ABSENT', 'Absent'), ('DISQUALIFIED', 'Disqualified'), ('PENDING', 'Pending')], db_index=True, help_text='Semester result status (PASS / FAIL / PROMOTED / ABSENT / DISQUALIFIED etc.)', max_length=20)),
                ('semester_max_credit', models.PositiveIntegerField()),
                ('semester_credit_earned', models.PositiveIntegerField()),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('next_semester', models.PositiveIntegerField(blank=True, null=True)),
                ('next_sem_status', models.CharField(blank=True, help_text='Next semester status (ELIGIBLE / NOT_ELIGIBLE / etc.)', max_length=15, null=True)),
                ('is_legacy', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='pg.pgstudentprofile')),
            ],
            options={
                'verbose_name': 'PG Exam Result',
                'verbose_name_plural': 'PG Exam Results',
                'indexes': [models.Index(fields=['student', 'semester'], name='pg_pgexamre_student_b9fc49_idx'), models.Index(fields=['semester', 'session'], name='pg_pgexamre_semeste_ac3e72_idx'), models.Index(fields=['semester_result'], name='pg_pgexamre_semeste_420b4c_idx')],
                'unique_together': {('student', 'semester', 'session')},
            },
        ),
    ]
