# Generated by Django 5.2.10 on 2026-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0021_pgexamresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcoursestructure',
            name='course_code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=20, null=True),
        ),
    ]
