# Generated by Django 5.2.10 on 2026-02-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0022_pgcoursestructure_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcoursestructure',
            name='effective_credit',
            field=models.IntegerField(blank=True, help_text='Effective Credit', null=True),
        ),
    ]
