# Generated by Django 5.2.10 on 2026-02-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0024_alter_pgexamresult_semester_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='is_cia_fill',
            field=models.BooleanField(default=False, help_text='Is CIA Fill'),
        ),
        migrations.AddField(
            model_name='pgstudentcourseassessment',
            name='is_ese_fill',
            field=models.BooleanField(default=False, help_text='Is ESE Fill'),
        ),
    ]
