# Generated by Django 5.2.10 on 2026-02-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0025_pgstudentcourseassessment_is_cia_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgexamregistration',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('BACK', 'Back'), ('IMPROVEMENT', 'Improvement')], default='REGULAR', help_text='Exam Type', max_length=20),
        ),
    ]
