# Generated by Django 5.2.10 on 2026-02-18 08:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('pg', '0029_alter_pgexamresult_semester_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_month_year', models.CharField(blank=True, max_length=20, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PGExamCenterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_colleges', models.ManyToManyField(related_name='pg_exam_centers', to='colleges.college')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_as_center_mappings', to='colleges.college')),
                ('exams', models.ManyToManyField(related_name='pg_center_mappings', to='pg.pgexam')),
            ],
            options={
                'verbose_name': 'PG Exam Center Mapping',
                'verbose_name_plural': 'PG Exam Center Mappings',
            },
        ),
        migrations.CreateModel(
            name='PGExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(blank=True, max_length=100, null=True)),
                ('sitting', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_course_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_exam_schedules', to='pg.pgcommoncoursestructure')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pg.pgexam')),
            ],
            options={
                'verbose_name': 'PG Exam Schedule',
                'verbose_name_plural': 'PG Exam Schedules',
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='PGGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pg_groups', to='pg.pgdepartment')),
            ],
        ),
    ]
