# Generated by Django 5.2.10 on 2026-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0030_pgexam_pgexamcentermapping_pgexamschedule_pggroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pggroup',
            name='department',
        ),
        migrations.AddField(
            model_name='pggroup',
            name='department',
            field=models.ManyToManyField(related_name='pg_groups', to='pg.pgdepartment'),
        ),
    ]
