# Generated by Django 5.2.10 on 2026-02-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0031_remove_pggroup_department_pggroup_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgexamschedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_exam_schedules', to='pg.pggroup'),
        ),
    ]
