# Generated by Django 5.2.10 on 2026-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0032_pgexamschedule_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pgcommoncoursestructure',
            options={'ordering': ['semester', 'course_name'], 'verbose_name': 'PGCommon Course Structure', 'verbose_name_plural': 'PGCommon Course Structures'},
        ),
        migrations.AlterField(
            model_name='pgexamregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('REGISTERED', 'Registered'), ('CLOSED', 'Closed')], default='PENDING', help_text='Registration Status', max_length=15),
        ),
    ]
