# Generated by Django 5.2.10 on 2026-02-19 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0033_alter_pgcommoncoursestructure_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGExamRegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.CharField(help_text='Unique order ID sent to CC Avenue', max_length=100, unique=True)),
                ('tracking_id', models.CharField(blank=True, help_text='CC Avenue tracking ID', max_length=100, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pg.pgexamregistration')),
            ],
            options={
                'verbose_name': 'PG Exam Registration Payment',
                'verbose_name_plural': 'PG Exam Registration Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
