# Generated by Django 5.2.10 on 2026-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0034_pg_exam_registration_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgexamregistration',
            name='addmtion_receipt',
            field=models.FileField(blank=True, help_text='Addmtion Receipt', null=True, upload_to='pg/addmtion_receipts/'),
        ),
    ]
