# Generated by Django 5.2.10 on 2026-02-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0035_pgexamregistration_addmtion_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pgstudentprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
