# Generated by Django 5.2.10 on 2026-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0036_pgstudentprofile_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pgexamregistration',
            name='addmtion_receipt',
        ),
        migrations.AddField(
            model_name='pgexamregistration',
            name='admission_receipt',
            field=models.FileField(blank=True, help_text='Admission Receipt', null=True, upload_to='pg/admission_receipts/'),
        ),
    ]
