# Generated by Django 5.2.10 on 2026-02-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0037_remove_pgexamregistration_addmtion_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgstudentprofile',
            name='medium_of_student',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
