# Generated by Django 5.2.10 on 2026-03-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0039_alter_pgexamregistration_admission_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgexamregistration',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Linked Exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registrations', to='pg.pgexam'),
        ),
    ]
