# Generated by Django 5.2.11 on 2026-03-09 18:04

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0040_pgexamregistration_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgexamregistration',
            name='admission_receipt',
            field=models.FileField(blank=True, help_text='Admission Receipt', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('pg/admission_receipts/')),
        ),
        migrations.AlterField(
            model_name='pgstudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('pg_students/profiles/')),
        ),
        migrations.AlterField(
            model_name='pgstudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('pg_students/signatures/')),
        ),
    ]
