# Generated by Django 5.2.10 on 2026-03-11 07:56

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0041_alter_pgexamregistration_admission_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgexamschedule',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pgexamschedule',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
