# Generated by Django 5.2.10 on 2026-01-23 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StagingInstituteMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institute_id', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=500, null=True)),
                ('institute_type', models.CharField(blank=True, max_length=255, null=True)),
                ('website_address', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('enrollment_process', models.TextField(blank=True, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliated_year', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.CharField(blank=True, max_length=255, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated to College table?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staging - Institute Master',
                'verbose_name_plural': 'Staging - Institute Master',
            },
        ),
    ]
