# Generated by Django 5.2.10 on 2026-01-23 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingApplicantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('reg_user_id', models.TextField(blank=True, help_text='reg_user_id', null=True)),
                ('center', models.TextField(blank=True, help_text='center', null=True)),
                ('applied_program', models.TextField(blank=True, help_text='applied_program', null=True)),
                ('first_name', models.TextField(blank=True, help_text='first_name', null=True)),
                ('mid_name', models.TextField(blank=True, help_text='mid_name', null=True)),
                ('last_name', models.TextField(blank=True, help_text='last_name', null=True)),
                ('full_name', models.TextField(blank=True, help_text='full_name', null=True)),
                ('applied_class', models.TextField(blank=True, help_text='applied_class', null=True)),
                ('exam_center_code', models.TextField(blank=True, help_text='exam_center_code', null=True)),
                ('gender', models.TextField(blank=True, help_text='gender', null=True)),
                ('nationality', models.TextField(blank=True, help_text='nationality', null=True)),
                ('dob', models.TextField(blank=True, help_text='dob', null=True)),
                ('dob_in_word', models.TextField(blank=True, help_text='dob_in_word', null=True)),
                ('blood_group', models.TextField(blank=True, help_text='blood_group', null=True)),
                ('caste', models.TextField(blank=True, help_text='caste', null=True)),
                ('second_language', models.TextField(blank=True, help_text='second_language', null=True)),
                ('univ_regn_no', models.TextField(blank=True, help_text='univ_regn_no', null=True)),
                ('category', models.TextField(blank=True, help_text='category', null=True)),
                ('is_general', models.TextField(blank=True, help_text='is_general', null=True)),
                ('is_physically_challanged', models.TextField(blank=True, help_text='is_physically_challanged', null=True)),
                ('instruction_mode', models.TextField(blank=True, help_text='instruction_mode', null=True)),
                ('last_grade', models.TextField(blank=True, help_text='last_grade', null=True)),
                ('last_board', models.TextField(blank=True, help_text='last_board', null=True)),
                ('present_status', models.TextField(blank=True, help_text='present_status', null=True)),
                ('employer_address', models.TextField(blank=True, help_text='employer_address', null=True)),
                ('comm_address_ref_id', models.TextField(blank=True, help_text='comm_address_ref_id', null=True)),
                ('perm_address_ref_id', models.TextField(blank=True, help_text='perm_address_ref_id', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='updated_on', null=True)),
                ('religion', models.TextField(blank=True, help_text='religion', null=True)),
                ('applicant_email', models.TextField(blank=True, help_text='applicant_email', null=True)),
                ('applicant_landline', models.TextField(blank=True, help_text='applicant_landline', null=True)),
                ('applicant_mobile', models.TextField(blank=True, help_text='applicant_mobile', null=True)),
                ('highest_qualification', models.TextField(blank=True, help_text='highest_qualification', null=True)),
                ('secured_mark', models.TextField(blank=True, help_text='secured_mark', null=True)),
                ('guardian_name', models.TextField(blank=True, help_text='guardian_name', null=True)),
                ('marital_status', models.TextField(blank=True, help_text='marital_status', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('record_status', models.TextField(blank=True, help_text='record_status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('discipline_code', models.TextField(blank=True, help_text='discipline_code', null=True)),
                ('aadhar_no', models.TextField(blank=True, help_text='aadhar_no', null=True)),
                ('medium', models.TextField(blank=True, help_text='medium', null=True)),
                ('applied', models.TextField(blank=True, help_text='applied', null=True)),
                ('applied_details', models.TextField(blank=True, help_text='applied_details', null=True)),
                ('application_status', models.TextField(blank=True, help_text='application_status', null=True)),
                ('differently_abled', models.TextField(blank=True, help_text='differently_abled', null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staging - Applicant Master',
                'verbose_name_plural': 'Staging - Applicant Master',
            },
        ),
    ]
