# Generated by Django 5.2.10 on 2026-01-23 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0002_stagingapplicantmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantRegMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('reg_user_id', models.TextField(blank=True, help_text='reg_user_id', null=True)),
                ('first_name', models.TextField(blank=True, help_text='first_name', null=True)),
                ('mid_name', models.TextField(blank=True, help_text='mid_name', null=True)),
                ('last_name', models.TextField(blank=True, help_text='last_name', null=True)),
                ('dob', models.TextField(blank=True, help_text='dob', null=True)),
                ('communication_flag', models.TextField(blank=True, help_text='communication_flag', null=True)),
                ('email_id', models.TextField(blank=True, help_text='email_id', null=True)),
                ('mobile', models.TextField(blank=True, help_text='mobile', null=True)),
                ('pin', models.TextField(blank=True, help_text='pin', null=True)),
                ('applied_program', models.TextField(blank=True, help_text='applied_program', null=True)),
                ('applied_date', models.TextField(blank=True, help_text='applied_date', null=True)),
                ('reg_mode', models.TextField(blank=True, help_text='reg_mode', null=True)),
                ('scrutiny_status', models.TextField(blank=True, help_text='scrutiny_status', null=True)),
                ('scrutiny_remark', models.TextField(blank=True, help_text='scrutiny_remark', null=True)),
                ('reg_status', models.TextField(blank=True, help_text='reg_status', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='updated_on', null=True)),
                ('status', models.TextField(blank=True, help_text='status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('dob1', models.TextField(blank=True, help_text='dob1', null=True)),
                ('mode', models.TextField(blank=True, help_text='mode', null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Applicant Reg Master',
                'verbose_name_plural': 'Applicant Reg Master',
            },
        ),
    ]
