# Generated by Django 5.2.10 on 2026-01-23 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0003_applicantregmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDisciplineSemPaperMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('scdsp_code', models.TextField(blank=True, help_text='scdsp_code', null=True)),
                ('syllabus_code', models.TextField(blank=True, help_text='syllabus_code', null=True)),
                ('course_code', models.TextField(blank=True, help_text='course_code', null=True)),
                ('discipline_code', models.TextField(blank=True, help_text='discipline_code', null=True)),
                ('semester_code', models.TextField(blank=True, help_text='semester_code', null=True)),
                ('paper_code', models.TextField(blank=True, help_text='paper_code', null=True)),
                ('paper_type', models.TextField(blank=True, help_text='paper_type', null=True)),
                ('subject_type', models.TextField(blank=True, help_text='subject_type', null=True)),
                ('paper_ge', models.TextField(blank=True, help_text='paper_ge', null=True)),
                ('paper_credit', models.TextField(blank=True, help_text='paper_credit', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('update_on', models.TextField(blank=True, help_text='update_on', null=True)),
                ('record_status', models.TextField(blank=True, help_text='record_status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Discipline Sem Paper Mapping',
                'verbose_name_plural': 'Course Discipline Sem Paper Mapping',
            },
        ),
        migrations.CreateModel(
            name='DisciplineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('discipline_code', models.TextField(blank=True, help_text='discipline_code', null=True)),
                ('discipline', models.TextField(blank=True, help_text='discipline', null=True)),
                ('discipline_name', models.TextField(blank=True, help_text='discipline_name', null=True)),
                ('discipline_name_new', models.TextField(blank=True, help_text='discipline_name_new', null=True)),
                ('subject_name', models.TextField(blank=True, help_text='subject_name', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='updated_on', null=True)),
                ('record_status', models.TextField(blank=True, help_text='record_status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('discipline_name_hindi', models.TextField(blank=True, help_text='discipline_name_hindi', null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discipline Master',
                'verbose_name_plural': 'Discipline Master',
            },
        ),
        migrations.CreateModel(
            name='PaperSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('scdsp_code', models.TextField(blank=True, help_text='scdsp_code', null=True)),
                ('paper_code', models.TextField(blank=True, help_text='paper_code', null=True)),
                ('subject_code', models.TextField(blank=True, help_text='subject_code', null=True)),
                ('discipline_code', models.TextField(blank=True, help_text='discipline_code', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('status', models.TextField(blank=True, help_text='status', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='updated_on', null=True)),
                ('record_status', models.TextField(blank=True, help_text='record_status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paper Subject Mapping',
                'verbose_name_plural': 'Paper Subject Mapping',
            },
        ),
        migrations.CreateModel(
            name='SubjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('subject_code', models.TextField(blank=True, help_text='subject_code', null=True)),
                ('subject_name', models.TextField(blank=True, help_text='subject_name', null=True)),
                ('syllabus_code', models.TextField(blank=True, help_text='syllabus_code', null=True)),
                ('semester_code', models.TextField(blank=True, help_text='semester_code', null=True)),
                ('mdc_subject_name', models.TextField(blank=True, help_text='mdc_subject_name', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='updated_on', null=True)),
                ('record_status', models.TextField(blank=True, help_text='record_status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject Master',
                'verbose_name_plural': 'Subject Master',
            },
        ),
    ]
