# Generated by Django 5.2.10 on 2026-01-23 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0004_coursedisciplinesempapermapping_disciplinemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredApplicantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('csv_id', models.TextField(blank=True, help_text='id', null=True)),
                ('reg_no', models.TextField(blank=True, help_text='reg_no', null=True)),
                ('sams_id', models.TextField(blank=True, help_text='sams_id', null=True)),
                ('college_roll_no', models.TextField(blank=True, help_text='college_roll_no', null=True)),
                ('college_reg_no', models.TextField(blank=True, help_text='college_reg_no', null=True)),
                ('center', models.TextField(blank=True, help_text='center', null=True)),
                ('center2017_old', models.TextField(blank=True, help_text='3rdcenter2017_old', null=True)),
                ('center2017', models.TextField(blank=True, help_text='3rdcenter2017', null=True)),
                ('roll_no', models.TextField(blank=True, help_text='roll_no', null=True)),
                ('result', models.TextField(blank=True, help_text='result', null=True)),
                ('exam_type_code', models.TextField(blank=True, help_text='exam_type_code', null=True)),
                ('student_name', models.TextField(blank=True, help_text='student_name', null=True)),
                ('fathers_name', models.TextField(blank=True, help_text='fathers_name', null=True)),
                ('mothers_name', models.TextField(blank=True, help_text='mothers_name', null=True)),
                ('appl_no', models.TextField(blank=True, help_text='appl_no', null=True)),
                ('course_code', models.TextField(blank=True, help_text='course_code', null=True)),
                ('discipline_code', models.TextField(blank=True, help_text='discipline_code', null=True)),
                ('semester_code', models.TextField(blank=True, help_text='semester_code', null=True)),
                ('batch_code', models.TextField(blank=True, help_text='batch_code', null=True)),
                ('syllabus_year', models.TextField(blank=True, help_text='syllabus_year', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='institute_code', null=True)),
                ('session_code', models.TextField(blank=True, help_text='session_code', null=True)),
                ('phone', models.TextField(blank=True, help_text='phone', null=True)),
                ('dob', models.TextField(blank=True, help_text='dob', null=True)),
                ('gender', models.TextField(blank=True, help_text='gender', null=True)),
                ('category', models.TextField(blank=True, help_text='category', null=True)),
                ('approve', models.TextField(blank=True, help_text='Approve', null=True)),
                ('full_address', models.TextField(blank=True, help_text='full_address', null=True)),
                ('institute_pub_status', models.TextField(blank=True, help_text='institute_pub_status', null=True)),
                ('student_pub_status', models.TextField(blank=True, help_text='student_pub_status', null=True)),
                ('last_board', models.TextField(blank=True, help_text='last_board', null=True)),
                ('aadhar_card_no', models.TextField(blank=True, help_text='aadhar_card_no', null=True)),
                ('created_by', models.TextField(blank=True, help_text='created_by', null=True)),
                ('created_on', models.TextField(blank=True, help_text='created_on', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='updated_by', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='updated_on', null=True)),
                ('record_status', models.TextField(blank=True, help_text='record_status', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='last_updated', null=True)),
                ('payment_status', models.TextField(blank=True, help_text='payment_status', null=True)),
                ('is_sem', models.TextField(blank=True, help_text='is_sem', null=True)),
                ('abc_id', models.TextField(blank=True, help_text='ABC_Id', null=True)),
                ('addmision_date', models.TextField(blank=True, help_text='Addmision_date', null=True)),
                ('api_status', models.TextField(blank=True, help_text='api_status', null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registered Applicant Master',
                'verbose_name_plural': 'Registered Applicant Master',
            },
        ),
    ]
