# Generated by Django 5.2.10 on 2026-01-24 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0005_registeredapplicantmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingApplicantQualificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('applied_class', models.TextField(blank=True, help_text='APPLIED_CLASS', null=True)),
                ('applied_program', models.TextField(blank=True, help_text='APPLIED_PROGRAM', null=True)),
                ('created_by', models.TextField(blank=True, help_text='CREATED_BY', null=True)),
                ('created_on', models.TextField(blank=True, help_text='CREATED_ON', null=True)),
                ('division_distinction', models.TextField(blank=True, help_text='DIVISION_DISTINCTION', null=True)),
                ('exam_code', models.TextField(blank=True, help_text='EXAM_CODE', null=True)),
                ('full_mark', models.TextField(blank=True, help_text='FULL_MARK', null=True)),
                ('grade', models.TextField(blank=True, help_text='GRADE', null=True)),
                ('grade_mark_flag', models.TextField(blank=True, help_text='GRADE_MARK_FLAG', null=True)),
                ('csv_id', models.TextField(blank=True, help_text='ID', null=True)),
                ('institute_code', models.TextField(blank=True, help_text='INSTITUTE_CODE', null=True)),
                ('institute_name', models.TextField(blank=True, help_text='INSTITUTE_NAME', null=True)),
                ('last_updated', models.TextField(blank=True, help_text='LAST_UPDATED', null=True)),
                ('mark_secured', models.TextField(blank=True, help_text='MARK_SECURED', null=True)),
                ('math_grade', models.TextField(blank=True, help_text='MATH_GRADE', null=True)),
                ('math_mark', models.TextField(blank=True, help_text='MATH_MARK', null=True)),
                ('percentage_mark', models.TextField(blank=True, help_text='PERCENTAGE_MARK', null=True)),
                ('qual_desc_1', models.TextField(blank=True, help_text='QUAL_DESC_1', null=True)),
                ('qual_desc_2', models.TextField(blank=True, help_text='QUAL_DESC_2', null=True)),
                ('reg_user_id', models.TextField(blank=True, help_text='REG_USER_ID', null=True)),
                ('roll_no', models.TextField(blank=True, help_text='ROLL_NO', null=True)),
                ('status', models.TextField(blank=True, help_text='STATUS', null=True)),
                ('subjects_offered', models.TextField(blank=True, help_text='SUBJECTS_OFFERED', null=True)),
                ('university_board', models.TextField(blank=True, help_text='UNIVERSITY_BOARD', null=True)),
                ('updated_by', models.TextField(blank=True, help_text='UPDATED_BY', null=True)),
                ('updated_on', models.TextField(blank=True, help_text='UPDATED_ON', null=True)),
                ('year_of_passing', models.TextField(blank=True, help_text='YEAR_OF_PASSING', null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staging - ApplicantQualificationDetail',
                'verbose_name_plural': 'Staging - ApplicantQualificationDetail',
            },
        ),
    ]
