# Generated by Django 5.2.10 on 2026-01-25 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0007_add_ugsemresultcurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGResultCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from dump', max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('college_roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('college_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=30, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=30, null=True)),
                ('session_code', models.CharField(blank=True, max_length=30, null=True)),
                ('course_code', models.CharField(blank=True, max_length=30, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=30, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=500, null=True)),
                ('faculty', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_type_his', models.CharField(blank=True, max_length=30, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=30, null=True)),
                ('maximum_mark', models.CharField(blank=True, max_length=20, null=True)),
                ('pass_mark', models.CharField(blank=True, max_length=20, null=True)),
                ('mark_secured', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_total_mark', models.CharField(blank=True, max_length=20, null=True)),
                ('subject_ca', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_ng', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_ce', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_gp', models.CharField(blank=True, max_length=50, null=True)),
                ('total_ca', models.CharField(blank=True, max_length=50, null=True)),
                ('total_ce', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result', models.CharField(blank=True, max_length=20, null=True)),
                ('final_result', models.CharField(blank=True, max_length=50, null=True)),
                ('grand_total_mark', models.CharField(blank=True, max_length=20, null=True)),
                ('total_secured_mark', models.CharField(blank=True, max_length=20, null=True)),
                ('total_per', models.CharField(blank=True, max_length=20, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gpa', models.CharField(blank=True, max_length=50, null=True)),
                ('cgpa', models.CharField(blank=True, max_length=50, null=True)),
                ('numrical_let_grad', models.CharField(blank=True, max_length=50, null=True)),
                ('let_grad_sub', models.CharField(blank=True, max_length=20, null=True)),
                ('let_grad', models.CharField(blank=True, max_length=50, null=True)),
                ('dsc_grad', models.CharField(blank=True, max_length=50, null=True)),
                ('agreegate', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('record_status', models.CharField(blank=True, max_length=20, null=True)),
                ('final_sheet_status', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name_hindi', models.CharField(blank=True, max_length=100, null=True)),
                ('max_total_mark', models.CharField(blank=True, max_length=20, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PG Result Current',
                'verbose_name_plural': 'PG Result Current',
                'indexes': [models.Index(fields=['user_id'], name='staging_pgr_user_id_1384b5_idx'), models.Index(fields=['college_roll_no'], name='staging_pgr_college_033a7e_idx'), models.Index(fields=['college_reg_no'], name='staging_pgr_college_002365_idx'), models.Index(fields=['semester_code'], name='staging_pgr_semeste_53572a_idx'), models.Index(fields=['batch_code'], name='staging_pgr_batch_c_2dbba3_idx'), models.Index(fields=['session_code'], name='staging_pgr_session_803c3a_idx'), models.Index(fields=['course_code'], name='staging_pgr_course__94bf6f_idx'), models.Index(fields=['institute_code'], name='staging_pgr_institu_e331e5_idx')],
            },
        ),
    ]
