# Generated by Django 5.2.10 on 2026-01-25 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0008_pgresultcurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineMasterDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from dump', max_length=50, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discipline', models.CharField(blank=True, max_length=100, null=True)),
                ('discipline_name', models.CharField(blank=True, max_length=100, null=True)),
                ('discipline_name_new', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=50, null=True)),
                ('record_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=50, null=True)),
                ('discipline_name_hindi', models.CharField(blank=True, max_length=2500, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Discipline Master Dump',
                'verbose_name_plural': 'Discipline Master Dump',
                'indexes': [models.Index(fields=['discipline_code'], name='staging_dis_discipl_155da3_idx'), models.Index(fields=['institute_code'], name='staging_dis_institu_91c978_idx')],
            },
        ),
    ]
