# Generated by Django 5.2.10 on 2026-01-26 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0009_disciplinemasterdump'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institute_id', models.CharField(blank=True, help_text='Original institute_id from dump', max_length=50, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=50, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_type', models.CharField(blank=True, max_length=100, null=True)),
                ('website_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('institute_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment_process', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('affiliated_year', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=50, null=True)),
                ('record_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update', models.CharField(blank=True, max_length=50, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'indexes': [models.Index(fields=['institute_code'], name='staging_col_institu_a73e99_idx'), models.Index(fields=['institute_name'], name='staging_col_institu_9ef715_idx')],
            },
        ),
    ]
