# Generated by Django 5.2.10 on 2026-01-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0010_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
