# Generated by Django 5.2.10 on 2026-02-10 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0011_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGResultCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from dump', max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('college_roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('college_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('session_code', models.CharField(blank=True, max_length=50, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=50, null=True)),
                ('temp_paper_code', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_code_correction', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code_correction', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=500, null=True)),
                ('theory', models.CharField(blank=True, max_length=50, null=True)),
                ('sessional', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('pra', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('pass_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_secured', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_secured_history', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_total_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result_1', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result_2', models.CharField(blank=True, max_length=50, null=True)),
                ('final_result', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_total_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('total_secured_mark_1', models.CharField(blank=True, max_length=50, null=True)),
                ('total_secured_mark_2', models.CharField(blank=True, max_length=50, null=True)),
                ('total_secured_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('hon', models.CharField(blank=True, max_length=50, null=True)),
                ('total_per', models.CharField(blank=True, max_length=50, null=True)),
                ('agreegate', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=50, null=True)),
                ('record_status_check', models.CharField(blank=True, max_length=50, null=True)),
                ('record_status', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('student_check', models.CharField(blank=True, max_length=50, null=True)),
                ('grace_chk', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_reult_com', models.CharField(blank=True, max_length=50, null=True)),
                ('ExRegular_chk', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_count', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type_his', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregate_hindi', models.TextField(blank=True, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UG Result Current',
                'verbose_name_plural': 'UG Result Current',
                'indexes': [models.Index(fields=['user_id'], name='staging_ugr_user_id_5eb502_idx'), models.Index(fields=['college_roll_no'], name='staging_ugr_college_d1530a_idx'), models.Index(fields=['college_reg_no'], name='staging_ugr_college_a2e96a_idx'), models.Index(fields=['semester_code'], name='staging_ugr_semeste_69d600_idx'), models.Index(fields=['batch_code'], name='staging_ugr_batch_c_9f5c5e_idx'), models.Index(fields=['session_code'], name='staging_ugr_session_2539dd_idx'), models.Index(fields=['course_code'], name='staging_ugr_course__18431e_idx'), models.Index(fields=['institute_code'], name='staging_ugr_institu_721d73_idx')],
            },
        ),
    ]
