# Generated by Django 5.2.10 on 2026-02-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0013_rename_ugresultcurrent_ugresultbeforecia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UGResultBeforeCIA',
            new_name='UGResultCurrent',
        ),
        migrations.AlterModelOptions(
            name='ugresultcurrent',
            options={'verbose_name': 'UG Result Current before CIA', 'verbose_name_plural': 'UG Result Current before CIA'},
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_user_id_5eb502_idx',
            old_name='staging_ugr_user_id_9b4087_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_college_d1530a_idx',
            old_name='staging_ugr_college_8b3153_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_college_a2e96a_idx',
            old_name='staging_ugr_college_d4b71a_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_semeste_69d600_idx',
            old_name='staging_ugr_semeste_0e3af7_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_batch_c_9f5c5e_idx',
            old_name='staging_ugr_batch_c_7694ca_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_session_2539dd_idx',
            old_name='staging_ugr_session_0b4fc2_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_course__18431e_idx',
            old_name='staging_ugr_course__409a5b_idx',
        ),
        migrations.RenameIndex(
            model_name='ugresultcurrent',
            new_name='staging_ugr_institu_721d73_idx',
            old_name='staging_ugr_institu_2d78d3_idx',
        ),
    ]
