# Generated by Django 5.2.10 on 2026-03-11 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0015_ugsemresultcurrent_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingLLBResultCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('college_roll_no', models.CharField(blank=True, max_length=30, null=True)),
                ('college_reg_no', models.CharField(blank=True, max_length=30, null=True)),
                ('student_name', models.CharField(blank=True, max_length=80, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=80, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=80, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('session_code', models.CharField(blank=True, max_length=20, null=True)),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=20, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=30, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=80, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=20, null=True)),
                ('maximum_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('pass_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('mark_secured', models.CharField(blank=True, max_length=10, null=True)),
                ('mark_secured_his', models.CharField(blank=True, max_length=10, null=True)),
                ('subject_total_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('subject_result', models.CharField(blank=True, max_length=10, null=True)),
                ('final_result', models.CharField(blank=True, max_length=10, null=True)),
                ('grand_total_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('total_secured_mark', models.CharField(blank=True, max_length=10, null=True)),
                ('total_secured_mark_his', models.CharField(blank=True, max_length=10, null=True)),
                ('total_per', models.CharField(blank=True, max_length=10, null=True)),
                ('agreegate', models.CharField(blank=True, max_length=30, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=10, null=True)),
                ('record_status', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_grace_chk', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_wise_grace_chk', models.CharField(blank=True, max_length=10, null=True)),
                ('total_grace_chk', models.CharField(blank=True, max_length=10, null=True)),
                ('final_grace_list', models.CharField(blank=True, max_length=10, null=True)),
                ('grace_chk', models.CharField(blank=True, max_length=10, null=True)),
                ('hon', models.CharField(blank=True, max_length=10, null=True)),
                ('spfc_chk', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_migrated', models.BooleanField(default=False)),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLB Result Current',
                'verbose_name_plural': 'LLB Result Current',
                'indexes': [models.Index(fields=['user_id'], name='staging_sta_user_id_b6bb2f_idx'), models.Index(fields=['college_roll_no'], name='staging_sta_college_e06346_idx'), models.Index(fields=['college_reg_no'], name='staging_sta_college_a91218_idx'), models.Index(fields=['semester_code'], name='staging_sta_semeste_cbb746_idx'), models.Index(fields=['batch_code'], name='staging_sta_batch_c_21f072_idx'), models.Index(fields=['session_code'], name='staging_sta_session_3a8d4a_idx'), models.Index(fields=['course_code'], name='staging_sta_course__34968a_idx'), models.Index(fields=['institute_code'], name='staging_sta_institu_2de35a_idx')],
            },
        ),
    ]
