# Generated by Django 5.2.10 on 2026-03-17 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0016_stagingllbresultcurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterInstituteMapPurnea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from dump', max_length=50, null=True)),
                ('center_code', models.CharField(blank=True, max_length=255, null=True)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('session_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sem', models.CharField(blank=True, max_length=255, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Center Institute Map Purnea',
                'verbose_name_plural': 'Center Institute Map Purnea',
                'indexes': [models.Index(fields=['center_code'], name='staging_cen_center__55a893_idx'), models.Index(fields=['institute_code'], name='staging_cen_institu_237043_idx'), models.Index(fields=['course_code'], name='staging_cen_course__f4aba6_idx'), models.Index(fields=['batch_code'], name='staging_cen_batch_c_4e6fa5_idx'), models.Index(fields=['session_code'], name='staging_cen_session_fb9f2e_idx')],
            },
        ),
    ]
