# Generated by Django 5.2.12 on 2026-03-23 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0016_stagingllbresultcurrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocationalResultCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from dump', max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('college_roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('college_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=50, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('session_code', models.CharField(blank=True, max_length=50, null=True)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('pass_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('mark_secured', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_total_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result', models.CharField(blank=True, max_length=50, null=True)),
                ('final_result', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_total_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('total_secured_mark', models.CharField(blank=True, max_length=50, null=True)),
                ('total_per', models.CharField(blank=True, max_length=50, null=True)),
                ('agreegate', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=50, null=True)),
                ('record_status', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result_1', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_result_2', models.CharField(blank=True, max_length=50, null=True)),
                ('hon', models.CharField(blank=True, max_length=50, null=True)),
                ('student_check', models.CharField(blank=True, max_length=50, null=True)),
                ('total_secured_mark_1', models.CharField(blank=True, max_length=50, null=True)),
                ('total_secured_mark_2', models.CharField(blank=True, max_length=50, null=True)),
                ('grace_chk', models.CharField(blank=True, max_length=50, null=True)),
                ('pra', models.CharField(blank=True, max_length=50, null=True)),
                ('paper_type_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discipline_code_temp', models.CharField(blank=True, max_length=50, null=True)),
                ('end_term_sum', models.CharField(blank=True, max_length=50, null=True)),
                ('lab_sum', models.CharField(blank=True, max_length=50, null=True)),
                ('is_migrated', models.BooleanField(default=False, help_text='Has this record been migrated?')),
                ('migration_notes', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vocational Result Current',
                'verbose_name_plural': 'Vocational Result Current',
                'indexes': [models.Index(fields=['user_id'], name='staging_voc_user_id_920840_idx'), models.Index(fields=['college_roll_no'], name='staging_voc_college_eb3b0a_idx'), models.Index(fields=['college_reg_no'], name='staging_voc_college_c25896_idx'), models.Index(fields=['semester_code'], name='staging_voc_semeste_c17c88_idx'), models.Index(fields=['batch_code'], name='staging_voc_batch_c_6003a9_idx'), models.Index(fields=['session_code'], name='staging_voc_session_0c8750_idx'), models.Index(fields=['course_code'], name='staging_voc_course__bf9535_idx'), models.Index(fields=['institute_code'], name='staging_voc_institu_770ff9_idx')],
            },
        ),
    ]
