# Generated by Django 5.2.10 on 2026-03-20 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0017_centerinstitutemappurnea'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMasterDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from dump', max_length=255, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_code', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_name', models.CharField(blank=True, max_length=500, null=True)),
                ('batch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('session_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('discipline_code', models.CharField(blank=True, max_length=255, null=True)),
                ('semester_code', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_all', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_exam_month', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('sl_no', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_month', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_year', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('apply_end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_mark_entry_date', models.CharField(blank=True, max_length=255, null=True)),
                ('online_payment_transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('omr_no', models.CharField(blank=True, max_length=255, null=True)),
                ('template_code', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_status', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staging - Exam Master Dump',
                'verbose_name_plural': 'Staging - Exam Master Dump',
            },
        ),
    ]
