# Generated by Django 5.2.10 on 2026-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0018_exammasterdump'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammasterdump',
            name='is_migrated',
            field=models.BooleanField(default=False, help_text='Has this record been migrated?'),
        ),
        migrations.AddField(
            model_name='exammasterdump',
            name='is_sem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exammasterdump',
            name='migration_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
