# Generated by Django 5.2.10 on 2026-03-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0019_exammasterdump_is_migrated_exammasterdump_is_sem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exammasterdump',
            options={'verbose_name': 'Exam Master Dump', 'verbose_name_plural': 'Exam Master Dump'},
        ),
    ]
