# Generated by Django 5.2.10 on 2026-03-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staging', '0017_vocationalresultcurrent'),
        ('staging', '0020_alter_exammasterdump_options'),
    ]

    operations = [
    ]
