# Generated by Django 5.2.10 on 2026-02-05 10:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btechstudentassessment',
            name='label',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PERIODICAL', 'Periodical Exam'), ('SESSIONAL', 'Sessional'), ('PRACTICAL', 'Practical'), ('PROJECT', 'Project'), ('SEMINAR', 'Seminar')], db_index=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BTechBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='btech.btechcourse')),
            ],
            options={
                'verbose_name': 'BTech Branch',
                'verbose_name_plural': 'BTech Branches',
            },
        ),
        migrations.AddField(
            model_name='btechbatch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='btech.btechbranch'),
        ),
        migrations.AddField(
            model_name='btechcommoncoursestructure',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_course_structures', to='btech.btechbranch'),
        ),
        migrations.AddField(
            model_name='btechcoursestructure',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='btech.btechbranch'),
        ),
        migrations.AddField(
            model_name='btechstudentprofile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='btech.btechbranch'),
        ),
    ]
