# Generated by Django 5.2.10 on 2026-02-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0002_alter_btechstudentassessment_label_btechbranch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechexamregistration',
            name='backlog_subjects',
            field=models.ManyToManyField(blank=True, related_name='backlog_registrations', to='btech.btechcommoncoursestructure'),
        ),
        migrations.AddField(
            model_name='btechexamregistration',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='btech.btechexam'),
        ),
        migrations.AddField(
            model_name='btechexamregistration',
            name='exam_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('BACK', 'Back'), ('IMPROVEMENT', 'Improvement')], default='REGULAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='btechstudentprofile',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SUSPENDED', 'Suspended'), ('ALUMNI', 'Alumni')], default='REGULAR', max_length=20),
        ),
    ]
