# Generated by Django 5.2.10 on 2026-02-05 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0003_btechexamregistration_backlog_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTechYearRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_eligible', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BTech Year Registration',
                'verbose_name_plural': 'BTech Year Registrations',
            },
        ),
        migrations.RemoveField(
            model_name='btechsemesterregistration',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='btechcommoncoursestructure',
            options={'ordering': ['year', 'course_name'], 'verbose_name': 'BTech Common Course Structure', 'verbose_name_plural': 'BTech Common Course Structures'},
        ),
        migrations.RemoveIndex(
            model_name='btechexamresult',
            name='btech_btech_student_02e16f_idx',
        ),
        migrations.RemoveIndex(
            model_name='btechexamresult',
            name='btech_btech_semeste_f2d9a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='btechstudentassessment',
            name='idx_btech_stud_sem',
        ),
        migrations.RemoveIndex(
            model_name='btechstudentassessment',
            name='idx_btech_batch_sem',
        ),
        migrations.RemoveIndex(
            model_name='btechstudentassessment',
            name='idx_btech_course_sem',
        ),
        migrations.RenameField(
            model_name='btechcommoncoursestructure',
            old_name='semester',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='btechexam',
            old_name='semester',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='btechexamregistration',
            old_name='sem',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='btechexamresult',
            old_name='next_semester',
            new_name='next_year',
        ),
        migrations.RenameField(
            model_name='btechexamresult',
            old_name='next_sem_status',
            new_name='next_year_status',
        ),
        migrations.RenameField(
            model_name='btechexamresult',
            old_name='semester',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='btechexamresult',
            old_name='semester_result',
            new_name='year_result',
        ),
        migrations.RenameField(
            model_name='btechstudentassessment',
            old_name='next_sem_status',
            new_name='next_year_status',
        ),
        migrations.RenameField(
            model_name='btechstudentassessment',
            old_name='semester',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='btechstudentassessment',
            old_name='sem_result',
            new_name='year_result',
        ),
        migrations.RenameField(
            model_name='btechstudentprofile',
            old_name='current_semester',
            new_name='current_year',
        ),
        migrations.RemoveField(
            model_name='btechcoursestructure',
            name='semester',
        ),
        migrations.AddField(
            model_name='btechcoursestructure',
            name='year',
            field=models.CharField(blank=True, help_text='Year', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='btechexamresult',
            unique_together={('student', 'year', 'session')},
        ),
        migrations.AddIndex(
            model_name='btechexamresult',
            index=models.Index(fields=['student', 'year'], name='btech_btech_student_8c7987_idx'),
        ),
        migrations.AddIndex(
            model_name='btechexamresult',
            index=models.Index(fields=['year_result'], name='btech_btech_year_re_da85f5_idx'),
        ),
        migrations.AddIndex(
            model_name='btechstudentassessment',
            index=models.Index(fields=['student', 'year'], name='idx_btech_stud_year'),
        ),
        migrations.AddIndex(
            model_name='btechstudentassessment',
            index=models.Index(fields=['batch', 'year'], name='idx_btech_batch_year'),
        ),
        migrations.AddIndex(
            model_name='btechstudentassessment',
            index=models.Index(fields=['course_code', 'year'], name='idx_btech_course_year'),
        ),
        migrations.AddField(
            model_name='btechyearregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_registrations', to='btech.btechstudentprofile'),
        ),
        migrations.DeleteModel(
            name='BTechSemesterRegistration',
        ),
    ]
