# Generated by Django 5.2.10 on 2026-02-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0004_btechyearregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechstudentprofile',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btechstudentprofile',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='btechstudentprofile',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
