# Generated by Django 5.2.10 on 2026-02-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0005_btechstudentprofile_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='btechexamcentermapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='btechexamcentermapping',
            name='exams',
            field=models.ManyToManyField(related_name='center_mappings', to='btech.btechexam'),
        ),
        migrations.RemoveField(
            model_name='btechexamcentermapping',
            name='exam',
        ),
    ]
