# Generated by Django 5.2.10 on 2026-02-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0006_alter_btechexamcentermapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btechexam',
            name='batch',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
