# Generated by Django 5.2.11 on 2026-03-09 18:04

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btech', '0007_btechexam_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btechstudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('btech_students/profiles/')),
        ),
        migrations.AlterField(
            model_name='btechstudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('btech_students/signatures/')),
        ),
    ]
