# Generated by Django 5.2.10 on 2026-01-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_degree_student_major_course_and_more'),
        ('ug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exam Registration', 'verbose_name_plural': 'Exam Registrations'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseassessment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Course Assessment', 'verbose_name_plural': 'Student Course Assessments'},
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='name',
            field=models.CharField(blank=True, help_text='Course Name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='json_data',
            field=models.JSONField(blank=True, help_text='JSON Data', null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated At'),
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At'),
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='json_data',
            field=models.JSONField(blank=True, help_text='JSON Data', null=True),
        ),
        migrations.AlterField(
            model_name='semesterregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated At'),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Created At'),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='json_data',
            field=models.JSONField(blank=True, help_text='JSON Data', null=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='ug_course_assessments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Updated At'),
        ),
        migrations.AlterUniqueTogether(
            name='studentcourseassessment',
            unique_together={('student', 'course_type', 'semester', 'label', 'exam_type')},
        ),
    ]
