# Generated by Django 5.2.10 on 2026-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0002_alter_examregistration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestructure',
            name='name',
            field=models.CharField(blank=True, help_text='Course Name', max_length=500, null=True),
        ),
    ]
