# Generated by Django 5.2.10 on 2026-01-24 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0004_ugstudentprofile_alter_examregistration_student_and_more'),
        ('university', '0005_alter_department_code_alter_university_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='e.g., B.A., B.Sc., B.Com., BCA', max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, help_text='e.g., BA, BSc', max_length=50, null=True)),
                ('total_semesters', models.PositiveIntegerField(default=8)),
                ('total_years', models.PositiveIntegerField(default=4)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UG Degree',
                'verbose_name_plural': 'UG Degrees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UGDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='e.g., History, Physics, Economics', max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('head_of_department', models.CharField(blank=True, max_length=255, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UG Department',
                'verbose_name_plural': 'UG Departments',
            },
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ug.ugdegree'),
        ),
        migrations.AlterField(
            model_name='coursestructure',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='ug.ugdepartment'),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ug.ugdepartment'),
        ),
        migrations.CreateModel(
            name='UGFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ug_faculties', to='university.university')),
            ],
            options={
                'verbose_name': 'UG Faculty',
                'verbose_name_plural': 'UG Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ugdepartment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='ug.ugfaculty'),
        ),
        migrations.CreateModel(
            name='UGProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Program name e.g., B.A. (Hons) History', max_length=255)),
                ('short_name', models.CharField(blank=True, help_text='e.g., BA History', max_length=50, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='ug.ugdegree')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='ug.ugdepartment')),
            ],
            options={
                'verbose_name': 'UG Program',
                'verbose_name_plural': 'UG Programs',
            },
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ug.ugprogram'),
        ),
    ]
