# Generated by Django 5.2.10 on 2026-01-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0006_ugbatch_coursestructure_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestructure',
            name='label',
            field=models.CharField(blank=True, help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100, null=True),
        ),
    ]
