# Generated by Django 5.2.10 on 2026-01-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0007_alter_coursestructure_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestructure',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='attendance',
            field=models.CharField(blank=True, help_text='Attendance', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='degree',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='ug.ugdepartment'),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='paper_code',
            field=models.CharField(blank=True, help_text='Paper Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coursestructure',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_structures', to='ug.ugdepartment'),
        ),
        migrations.AlterField(
            model_name='coursestructure',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_assessments', to='ug.ugbatch'),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester', max_length=20, null=True),
        ),
    ]
