# Generated by Django 5.2.10 on 2026-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0008_coursestructure_paper_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
