# Generated by Django 5.2.10 on 2026-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0009_alter_ugstudentprofile_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugstudentprofile',
            name='apaar_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
