# Generated by Django 5.2.10 on 2026-01-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0010_ugstudentprofile_apaar_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourseassessment',
            unique_together=set(),
        ),
    ]
