# Generated by Django 5.2.10 on 2026-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0012_commoncoursestructure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestructure',
            old_name='code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='studentcourseassessment',
            old_name='code',
            new_name='course_code',
        ),
        migrations.AddField(
            model_name='commoncoursestructure',
            name='code',
            field=models.CharField(blank=True, help_text='Course Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='short_name',
            field=models.CharField(blank=True, help_text="Course Short Name (e.g., 'IM' for 'Introductory Microeconomics').", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='short_name',
            field=models.CharField(blank=True, help_text="Course Short Name (e.g., 'IM' for 'Introductory Microeconomics').", max_length=250, null=True),
        ),
    ]
