# Generated by Django 5.2.10 on 2026-01-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0013_rename_code_coursestructure_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugstudentprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='is_absent',
            field=models.BooleanField(default=True, help_text='Is Absent'),
        ),
    ]
