# Generated by Django 5.2.10 on 2026-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0015_studentcourseassessment_final_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='college_code',
            field=models.CharField(blank=True, help_text='College Code', max_length=10, null=True),
        ),
    ]
