# Generated by Django 5.2.10 on 2026-01-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0016_studentcourseassessment_college_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursestructure',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='coursestructure',
            old_name='short_name',
            new_name='course_short_name',
        ),
        migrations.RenameField(
            model_name='studentcourseassessment',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='studentcourseassessment',
            old_name='short_name',
            new_name='course_short_name',
        ),
        migrations.RenameField(
            model_name='studentcourseassessment',
            old_name='is_absent',
            new_name='ind_is_absent',
        ),
        migrations.RemoveField(
            model_name='coursestructure',
            name='min_credit',
        ),
        migrations.RemoveField(
            model_name='coursestructure',
            name='min_mark',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='credit_obtained',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='exam_result',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='final_result',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='grace_mark',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='is_grace',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='max_credit',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='max_marks',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='min_credit',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='min_mark',
        ),
        migrations.RemoveField(
            model_name='studentcourseassessment',
            name='numeric_grade',
        ),
        migrations.AddField(
            model_name='coursestructure',
            name='min_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pass Mark', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total CREDIT OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_letter_grade',
            field=models.CharField(blank=True, help_text='Total LETTER GRADE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_max_credits',
            field=models.IntegerField(blank=True, help_text='Total MAX CREDIT', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_max_marks',
            field=models.IntegerField(blank=True, help_text='Total MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course CREDIT OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course GRACE MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course GRADE POINT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_max_credits',
            field=models.IntegerField(blank=True, help_text='Course MAX CREDIT', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_max_marks',
            field=models.IntegerField(blank=True, help_text='Course MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='course_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='ind_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='ind_max_marks',
            field=models.IntegerField(blank=True, help_text='Individual MAX MARKS', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='ind_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual PASS MARKS', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='next_sem_status',
            field=models.CharField(blank=True, help_text='Next Semester Status eg: eligible/not eligible', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='sem_credit_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester CREDIT OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='sem_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='sem_max_credit',
            field=models.IntegerField(blank=True, help_text='Semester MAX CREDIT', null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='sem_result',
            field=models.CharField(blank=True, help_text='Semester Result eg: pass/fail/promoted', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='sgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Semester GRADE POINT', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursestructure',
            name='max_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course Marks', max_digits=10, null=True),
        ),
    ]
