# Generated by Django 5.2.10 on 2026-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0017_rename_name_coursestructure_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_numeric_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total NUMERIC GRADE', max_digits=10, null=True),
        ),
    ]
