# Generated by Django 5.2.10 on 2026-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0018_studentcourseassessment_comb_numeric_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='temp_total_gp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total GRADE POINT', max_digits=10, null=True),
        ),
    ]
