# Generated by Django 5.2.10 on 2026-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0019_studentcourseassessment_temp_total_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='course_type',
            field=models.CharField(blank=True, db_index=True, help_text='Course Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='exam_type',
            field=models.CharField(blank=True, db_index=True, help_text='Type Regular/Back', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='ind_is_absent',
            field=models.BooleanField(db_index=True, default=True, help_text='Is Absent'),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='label',
            field=models.CharField(db_index=True, help_text='Assessment label (e.g. CIA-Theory, ESE-Practical)', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='paper_code',
            field=models.CharField(blank=True, db_index=True, help_text='Paper Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='semester',
            field=models.CharField(blank=True, db_index=True, help_text='Semester', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='session',
            field=models.CharField(blank=True, db_index=True, help_text='Session', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['student', 'semester'], name='idx_student_sem'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['student', 'semester', 'label'], name='idx_stud_sem_label'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['department', 'semester'], name='idx_dept_sem'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['department', 'semester', 'label'], name='idx_dept_sem_label'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['batch', 'semester'], name='idx_batch_sem'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['paper_code', 'semester'], name='idx_paper_sem'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['semester', 'label'], name='idx_sem_label'),
        ),
    ]
