# Generated by Django 5.2.10 on 2026-01-28 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0020_add_indexes_student_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('semester', models.PositiveIntegerField()),
                ('session', models.CharField(db_index=True, max_length=10)),
                ('cia_pass', models.BooleanField()),
                ('ese_pass', models.BooleanField()),
                ('semester_result', models.CharField(choices=[('PASS', 'Pass'), ('PROMOTED', 'Promoted'), ('FAIL', 'Fail'), ('ABSENT', 'Absent'), ('QUALIFIED', 'Qualified'), ('DISQUALIFIED', 'Disqualified'), ('PARTLY_QUALIFIED', 'Partly Qualified')], db_index=True, help_text='Semester result status (PASS / FAIL / PROMOTED / ABSENT / DISQUALIFIED etc.)', max_length=20)),
                ('semester_max_credit', models.PositiveIntegerField()),
                ('semester_credit_earned', models.PositiveIntegerField()),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('next_semester', models.PositiveIntegerField(blank=True, null=True)),
                ('next_sem_status', models.CharField(blank=True, help_text='Next semester status (ELIGIBLE / NOT_ELIGIBLE / etc.)', max_length=15, null=True)),
                ('is_legacy', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='ug.ugstudentprofile')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'indexes': [models.Index(fields=['student', 'semester'], name='ug_ugexamre_student_a2b5a4_idx'), models.Index(fields=['semester', 'session'], name='ug_ugexamre_semeste_1e5b9e_idx'), models.Index(fields=['semester_result'], name='ug_ugexamre_semeste_c54008_idx')],
                'unique_together': {('student', 'semester', 'session')},
            },
        ),
    ]
