# Generated by Django 5.2.10 on 2026-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0021_ugexamresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugexamresult',
            name='semester',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
