# Generated by Django 5.2.10 on 2026-01-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0022_alter_ugexamresult_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='ind_final_marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual FINAL MARKS OBTAINED', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='ind_grace_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual GRACE MARKS OBTAINED', max_digits=10, null=True),
        ),
    ]
