# Generated by Django 5.2.10 on 2026-01-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0023_studentcourseassessment_ind_final_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='comb_grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total GRADE POINT', max_digits=10, null=True),
        ),
    ]
