# Generated by Django 5.2.10 on 2026-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0024_studentcourseassessment_comb_grade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='ind_is_pass',
            field=models.BooleanField(blank=True, help_text='Is Pass', null=True),
        ),
    ]
