# Generated by Django 5.2.10 on 2026-01-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0025_studentcourseassessment_ind_is_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugexamresult',
            name='cia_pass',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ugexamresult',
            name='ese_pass',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
