# Generated by Django 5.2.10 on 2026-02-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0026_alter_ugexamresult_cia_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='major_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_courses', to='ug.ugdepartment'),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='mdc_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mdc_courses', to='ug.ugdepartment'),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='minor_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_courses', to='ug.ugdepartment'),
        ),
    ]
