# Generated by Django 5.2.10 on 2026-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0027_alter_ugstudentprofile_major_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugdepartment',
            name='faculty',
        ),
        migrations.AddField(
            model_name='ugdepartment',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ugfaculty',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='faculties', to='ug.ugdepartment'),
        ),
    ]
