# Generated by Django 5.2.10 on 2026-02-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0028_remove_ugdepartment_faculty_ugdepartment_is_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugfaculty',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
