# Generated by Django 5.2.10 on 2026-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0029_ugfaculty_is_publish'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='semesterregistration',
            index=models.Index(fields=['student', 'sem', 'is_open', 'status'], name='idx_eligibility_check'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['student', 'semester', 'session', 'paper_code', 'label', 'exam_type'], name='idx_reg_dup_check'),
        ),
    ]
