# Generated by Django 5.2.10 on 2026-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0030_semesterregistration_idx_eligibility_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('REGISTERED', 'Registered'), ('CLOSED', 'Closed')], default='PENDING', help_text='Registration Status', max_length=15),
        ),
    ]
