# Generated by Django 5.2.10 on 2026-02-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0031_add_registration_status_choices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='semesterregistration',
            name='idx_eligibility_check',
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Student Batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_registrations', to='ug.ugbatch'),
        ),
        migrations.AddIndex(
            model_name='semesterregistration',
            index=models.Index(fields=['student', 'sem', 'status'], name='idx_eligibility_check_v2'),
        ),
        migrations.AddIndex(
            model_name='semesterregistration',
            index=models.Index(fields=['batch', 'sem', 'status'], name='idx_batch_sem_status'),
        ),
    ]
