# Generated by Django 5.2.10 on 2026-02-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0032_add_batch_to_semester_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Student Batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ug.ugbatch'),
        ),
    ]
