# Generated by Django 5.2.11 on 2026-03-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0034_increase_sem_result_length_add_session_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseassessment',
            name='cia_filled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='is_cia_filled',
            field=models.BooleanField(default=False),
        ),
    ]
