# Generated by Django 5.2.11 on 2026-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0035_studentcourseassessment_cia_filled_on_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentcourseassessment',
            index=models.Index(fields=['college_code', 'session', 'semester', 'course_type'], name='idx_college_cia_entry'),
        ),
    ]
