# Generated by Django 5.2.11 on 2026-03-09 12:28

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0037_examregistrationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='admission_receipt',
            field=models.FileField(blank=True, help_text='Admission Receipt', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug/admission_receipts/')),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('BACK', 'Back')], default='REGULAR', help_text='Exam Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OPEN', 'Open'), ('REGISTERED', 'Registered'), ('CLOSED', 'Closed')], default='PENDING', help_text='Registration Status', max_length=15),
        ),
    ]
