# Generated by Django 5.2.11 on 2026-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0038_examregistration_admission_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugstudentprofile',
            name='medium_of_student',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ugstudentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ugstudentprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
