# Generated by Django 5.2.11 on 2026-03-22 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('ug', '0040_alter_examregistration_admission_receipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('exam_month_year', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UG Exam',
                'verbose_name_plural': 'UG Exams',
            },
        ),
        migrations.CreateModel(
            name='UGExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_time', models.CharField(blank=True, max_length=100, null=True)),
                ('sitting', models.CharField(blank=True, max_length=50, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('common_course_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='ug.commoncoursestructure')),
                ('course_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='ug.coursestructure')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ug.ugexam')),
            ],
            options={
                'verbose_name': 'UG Exam Schedule',
                'verbose_name_plural': 'UG Exam Schedules',
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='UGExamCenterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_colleges', models.ManyToManyField(related_name='ug_exam_centers', to='colleges.college')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ug_as_center_mappings', to='colleges.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_mappings', to='ug.ugexam')),
            ],
            options={
                'verbose_name': 'UG Exam Center Mapping',
                'verbose_name_plural': 'UG Exam Center Mappings',
                'unique_together': {('exam', 'center')},
            },
        ),
    ]
