# Generated by Django 5.2.11 on 2026-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0040_studentcourseassessment_is_migrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseassessment',
            name='is_migrated',
            field=models.BooleanField(default=False),
        ),
    ]
