# Generated by Django 5.2.11 on 2026-03-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0041_ugexam_ugexamschedule_ugexamcentermapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugexamschedule',
            name='common_course_structure',
        ),
        migrations.RemoveField(
            model_name='ugexamschedule',
            name='course_structure',
        ),
        migrations.AddField(
            model_name='ugexamschedule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='ug.ugdepartment'),
        ),
    ]
