# Generated by Django 5.2.11 on 2026-03-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0042_remove_ugexamschedule_common_course_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugexamschedule',
            name='department',
        ),
        migrations.AddField(
            model_name='ugexamschedule',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='exam_schedules', to='ug.ugdepartment'),
        ),
    ]
