# Generated by Django 5.2.12 on 2026-03-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0043_remove_ugexamschedule_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugexamschedule',
            name='mjc',
            field=models.ManyToManyField(blank=True, related_name='exam_mjc', to='ug.ugdepartment'),
        ),
    ]
