# Generated by Django 5.2.12 on 2026-03-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0041_alter_studentcourseassessment_is_migrated'),
        ('ug', '0044_ugexamschedule_mjc'),
    ]

    operations = [
    ]
