# Generated by Django 5.2.12 on 2026-03-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0045_merge_20260323_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugexamschedule',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
