# Generated by Django 5.2.12 on 2026-03-23 12:55

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0046_ugexamschedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='assessment',
            field=models.ManyToManyField(blank=True, related_name='exam_registrations', to='ug.studentcourseassessment'),
        ),
        migrations.AddField(
            model_name='semesterregistration',
            name='assessment',
            field=models.ManyToManyField(blank=True, related_name='semester_registrations', to='ug.studentcourseassessment'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='admission_receipt',
            field=models.FileField(blank=True, help_text='Admission Receipt', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug/admission_receipts/')),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug_students/profiles/')),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug_students/signatures/')),
        ),
    ]
