# Generated by Django 5.2.12 on 2026-03-24 06:37

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0047_examregistration_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ugexamschedule',
            name='subject',
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='admission_receipt',
            field=models.FileField(blank=True, help_text='Admission Receipt', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='D:\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug/admission_receipts/')),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='D:\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug_students/profiles/')),
        ),
        migrations.AlterField(
            model_name='ugstudentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='D:\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('ug_students/signatures/')),
        ),
    ]
