# Generated by Django 5.2.12 on 2026-03-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0048_remove_ugexamschedule_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugexamschedule',
            name='exam_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ug.coursestructure'),
        ),
        migrations.AddField(
            model_name='ugexamschedule',
            name='exam_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
