# Generated by Django 5.2.12 on 2026-03-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('ug', '0049_ugexamschedule_exam_subject_ugexamschedule_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugexamcentermapping',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ug_as_center_mappings', to='colleges.college'),
        ),
    ]
