# Generated by Django 5.2.12 on 2026-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0050_alter_ugexamcentermapping_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestructure',
            name='new_course_code',
            field=models.CharField(blank=True, help_text='Updated Course Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseassessment',
            name='new_course_code',
            field=models.CharField(blank=True, help_text='Updated Course Code', max_length=20, null=True),
        ),
    ]
