# Generated by Django 5.2.12 on 2026-03-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0051_coursestructure_new_course_code_and_studentcourseassessment_new_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ug.ugexam'),
        ),
    ]
