# Generated by Django 5.2.12 on 2026-03-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug', '0052_examregistration_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugexamschedule',
            name='attendance_from',
            field=models.DateTimeField(blank=True, help_text='Attendance start date and time', null=True),
        ),
        migrations.AddField(
            model_name='ugexamschedule',
            name='attendance_to',
            field=models.DateTimeField(blank=True, help_text='Attendance end date and time', null=True),
        ),
    ]
