# Generated by Django 6.0.1 on 2026-01-20 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department', 'name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='program',
            name='college',
        ),
        migrations.CreateModel(
            name='CourseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='e.g., Major Course 1, SEC 2', max_length=100)),
                ('sequence_number', models.PositiveIntegerField(help_text='Sequence number (1, 2, 3...)')),
                ('sequence_name', models.CharField(blank=True, help_text='e.g., MJC-1, SEC-2', max_length=50, null=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=100, help_text='Total marks for this slot')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_slots', to='academics.coursetype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_slots', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Course Slot',
                'verbose_name_plural': 'Course Slots',
                'ordering': ['semester', 'course_type', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='BatchCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_structure', to='academics.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_structures', to='academics.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_course_structure', to='academics.program')),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_courses', to='academics.courseslot')),
            ],
            options={
                'verbose_name': 'Batch Course Structure',
                'verbose_name_plural': 'Batch Course Structures',
                'ordering': ['batch', 'program', 'course_slot'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('head_of_department', models.CharField(blank=True, max_length=255, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='academics.department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department'),
        ),
        migrations.CreateModel(
            name='ProgramCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_structures', to='academics.course')),
                ('course_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academics.courseslot')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_structure', to='academics.program')),
            ],
            options={
                'verbose_name': 'Program Course Structure',
                'verbose_name_plural': 'Program Course Structures',
                'ordering': ['program', 'course_slot'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
