# Generated by Django 5.2.10 on 2026-01-29 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plwresultdetail',
            name='marks_obtained',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plwresultdetail',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='plw.plwresult'),
        ),
        migrations.AlterField(
            model_name='plwresultdetail',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='plw.plwsubject'),
        ),
    ]
