# Generated by Django 6.0.1 on 2026-01-15 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('address', models.TextField()),
                ('vice_chancellor', models.CharField(max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('established_date', models.DateField()),
                ('website', models.URLField(blank=True, unique=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'indexes': [models.Index(fields=['name'], name='university__name_6469b2_idx'), models.Index(fields=['short_name'], name='university__short_n_e271e5_idx')],
            },
        ),
    ]
