# Generated by Django 5.2.10 on 2026-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_faculty_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, help_text='e.g., History, Physics,Economics,Mathematics', max_length=255, null=True),
        ),
    ]
