# Generated by Django 5.2.10 on 2026-02-04 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0008_college_college_name_hindi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRegistrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='NewRegistrationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewRegistrationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='NewRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='voc_registrations/images/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='voc_registrations/signatures/')),
                ('migration_certificate', models.ImageField(blank=True, null=True, upload_to='voc_registrations/certificates/')),
                ('registration_certificate', models.ImageField(blank=True, null=True, upload_to='voc_registrations/certificates/')),
                ('student_name', models.CharField(help_text='Student name in English', max_length=255)),
                ('student_name_hindi', models.CharField(blank=True, help_text='Student name in Hindi', max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('caste', models.CharField(blank=True, choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('EBC', 'EBC'), ('RBC', 'RBC'), ('FDC', 'FDC')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_no', models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, null=True)),
                ('apaar_no', models.CharField(blank=True, help_text='12-digit Apaar number', max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('migration_submitted', models.BooleanField(default=False)),
                ('migrated_from_other_university', models.BooleanField(default=False)),
                ('last_attended_university', models.CharField(blank=True, max_length=255, null=True)),
                ('old_registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_account_created', models.BooleanField(default=False)),
                ('is_registration_completed', models.BooleanField(default=False)),
                ('registration_number', models.CharField(blank=True, help_text='Generated unique registration number', max_length=50, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('json_data', models.JSONField(blank=True, help_text='Additional data from Excel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, help_text='College where student is registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_new_registrations', to='colleges.college')),
                ('batch', models.ForeignKey(blank=True, help_text='Vocational Batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='voc_new_registration.newregistrationbatch')),
                ('course', models.ForeignKey(blank=True, help_text='Vocational Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='voc_new_registration.newregistrationcourse')),
                ('session', models.ForeignKey(blank=True, help_text='Vocational Session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='voc_new_registration.newregistrationsession')),
            ],
            options={
                'verbose_name': 'VOC New Registration',
                'verbose_name_plural': 'VOC New Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Unique order ID sent to CC Avenue', max_length=100, unique=True)),
                ('tracking_id', models.CharField(blank=True, help_text='CC Avenue tracking ID', max_length=100, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='voc_new_registration.newregistration')),
            ],
            options={
                'verbose_name': 'VOC Registration Payment',
                'verbose_name_plural': 'VOC Registration Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newregistration',
            index=models.Index(fields=['student_name'], name='voc_new_reg_student_07355f_idx'),
        ),
        migrations.AddIndex(
            model_name='newregistration',
            index=models.Index(fields=['course'], name='voc_new_reg_course__6f5ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='newregistration',
            index=models.Index(fields=['college'], name='voc_new_reg_college_211690_idx'),
        ),
        migrations.AddIndex(
            model_name='newregistration',
            index=models.Index(fields=['aadhaar_no'], name='voc_new_reg_aadhaar_351060_idx'),
        ),
    ]
