# Generated by Django 5.2.10 on 2026-01-24 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0007_college_degree_offered'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocNewRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_name', models.CharField(help_text='Student name in English', max_length=255)),
                ('student_name_hindi', models.CharField(blank=True, help_text='Student name in Hindi', max_length=255, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('course', models.CharField(help_text='Course code (e.g., B.ED, M.ED)', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('caste', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('EBC', 'EBC'), ('RBC', 'RBC'), ('FDC', 'FDC')], max_length=10)),
                ('dob', models.DateField(help_text='Date of Birth')),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_no', models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admission_only', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=3)),
                ('last_attended_university', models.CharField(blank=True, max_length=255, null=True)),
                ('json_data', models.JSONField(blank=True, help_text='Additional data from Excel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(help_text='College where student is registered', on_delete=django.db.models.deletion.CASCADE, related_name='voc_new_registrations', to='colleges.college')),
            ],
            options={
                'verbose_name': 'VOC New Registration',
                'verbose_name_plural': 'VOC New Registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_name'], name='voc_new_reg_student_4f4952_idx'), models.Index(fields=['course'], name='voc_new_reg_course_23e912_idx'), models.Index(fields=['college'], name='voc_new_reg_college_37677a_idx'), models.Index(fields=['aadhaar_no'], name='voc_new_reg_aadhaar_d681d1_idx')],
            },
        ),
    ]
