# Generated by Django 5.2.10 on 2026-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregistration',
            name='sr_no',
            field=models.IntegerField(blank=True, help_text='Serial number (last 5 digits of registration number)', null=True),
        ),
    ]
