# Generated by Django 5.2.10 on 2026-01-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_professor_department_alter_course_department_and_more'),
        ('voc_new_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vocnewregistration',
            new_name='voc_new_reg_course__35588c_idx',
            old_name='voc_new_reg_course_23e912_idx',
        ),
        migrations.AddField(
            model_name='vocnewregistration',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Linked to Academics Batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_registrations_batch', to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='caste',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('EBC', 'EBC'), ('RBC', 'RBC'), ('FDC', 'FDC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Linked to Academics Course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_registrations_course', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
