# Generated by Django 5.2.10 on 2026-02-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('voc_new_registration', '0002_newregistration_sr_no'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='newregistration',
            index=models.Index(fields=['-sr_no'], name='voc_new_reg_sr_no_dcc342_idx'),
        ),
    ]
