# Generated by Django 5.2.10 on 2026-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0002_rename_voc_new_reg_course_23e912_idx_voc_new_reg_course__35588c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocnewregistration',
            name='admission_only',
        ),
        migrations.AddField(
            model_name='vocnewregistration',
            name='is_account_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocnewregistration',
            name='is_registration_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocnewregistration',
            name='migrated_from_other_university',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocnewregistration',
            name='migration_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
