# Generated by Django 5.2.10 on 2026-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0003_remove_vocnewregistration_admission_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocnewregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='voc_registrations/images/'),
        ),
        migrations.AddField(
            model_name='vocnewregistration',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='voc_registrations/signatures/'),
        ),
    ]
