# Generated by Django 5.2.10 on 2026-02-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0003_newregistration_voc_new_reg_sr_no_dcc342_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistration',
            name='caste',
            field=models.CharField(blank=True, choices=[('GEN', 'GEN'), ('General', 'General'), ('GEN.', 'GEN.'), ('UR', 'UR'), ('Unreserved', 'Unreserved'), ('OBC', 'OBC'), ('BC', 'BC'), ('BC-I', 'BC-I'), ('BC-II', 'BC-II'), ('BC (Annexure-II)', 'BC (Annexure-II)'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('EBC', 'EBC'), ('EBC-I', 'EBC-I'), ('EBC (Annexure-I)', 'EBC (Annexure-I)')], max_length=255, null=True),
        ),
    ]
