# Generated by Django 5.2.10 on 2026-01-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_college_degree_offered'),
        ('voc_new_registration', '0004_vocnewregistration_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocnewregistration',
            name='college',
            field=models.ForeignKey(blank=True, help_text='College where student is registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_new_registrations', to='colleges.college'),
        ),
    ]
