# Generated by Django 5.2.10 on 2026-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0004_alter_newregistration_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistration',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='voc_registrations/certificates/'),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='voc_registrations/certificates/'),
        ),
    ]
