# Generated by Django 5.2.10 on 2026-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0005_alter_newregistration_migration_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistration',
            name='caste',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('EWS', 'EWS'), ('OBC', 'OBC'), ('BC', 'BC'), ('BC-I', 'BC-I'), ('BC-II', 'BC-II'), ('BC (Annexure-II)', 'BC (Annexure-II)'), ('SC', 'SC'), ('ST', 'ST'), ('EBC', 'EBC'), ('EBC-I', 'EBC-I'), ('EBC (Annexure-I)', 'EBC (Annexure-I)')], max_length=255, null=True),
        ),
    ]
