# Generated by Django 5.2.10 on 2026-01-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_professor_department_alter_course_department_and_more'),
        ('voc_new_registration', '0005_alter_vocnewregistration_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocnewregistration',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Linked to Academics Session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voc_registrations_session', to='academics.session'),
        ),
    ]
