# Generated by Django 5.2.10 on 2026-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0006_vocnewregistration_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocnewregistration',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
