# Generated by Django 5.2.10 on 2026-02-11 18:44

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0006_alter_newregistration_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregistration',
            name='registration_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when registration was completed', null=True),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\code\\Purnea\\pup-umis-backend\\media\\documents'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/certificates/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\code\\Purnea\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/images/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\code\\Purnea\\pup-umis-backend\\media\\documents'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/certificates/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\code\\Purnea\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/signatures/')),
        ),
    ]
