# Generated by Django 5.2.10 on 2026-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0007_vocnewregistration_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocnewregistration',
            name='apaar',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, null=True),
        ),
    ]
