# Generated by Django 5.2.10 on 2026-02-12 07:24

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0007_newregistration_registration_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistration',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/documents/', location='documents'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/certificates/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/images/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/documents/', location='documents'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/certificates/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/signatures/')),
        ),
    ]
