# Generated by Django 5.2.10 on 2026-01-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0008_vocnewregistration_apaar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocnewregistration',
            old_name='apaar',
            new_name='apaar_no',
        ),
    ]
