# Generated by Django 5.2.10 on 2026-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0008_alter_newregistration_migration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregistrationcourse',
            name='registration_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Registration end date and time', null=True),
        ),
        migrations.AddField(
            model_name='newregistrationcourse',
            name='registration_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Registration start date and time', null=True),
        ),
    ]
