# Generated by Django 5.2.12 on 2026-03-31 18:53

import django.core.files.storage
import pup_umis_backend.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0009_newregistrationcourse_registration_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newregistration',
            name='migration_certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/documents/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\documents'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/certificates/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/images/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/documents/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\documents'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/certificates/')),
        ),
        migrations.AlterField(
            model_name='newregistration',
            name='signature',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/media/uploads/', location='C:\\Users\\PRADEEP\\OneDrive\\Desktop\\zcol\\pup-umis-backend\\media\\media/uploads'), upload_to=pup_umis_backend.upload_paths.UniqueFilePath('voc_registrations/signatures/')),
        ),
    ]
