# Generated by Django 5.2.10 on 2026-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0009_rename_apaar_vocnewregistration_apaar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocnewregistration',
            name='old_registration_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocnewregistration',
            name='apaar_no',
            field=models.CharField(blank=True, help_text='12-digit Apaar number', max_length=12, null=True),
        ),
    ]
