# Generated by Django 5.2.10 on 2026-01-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0010_vocnewregistration_old_registration_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocnewregistration',
            name='registration_no',
            field=models.CharField(blank=True, help_text='Generated after successful payment', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VocRegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='Unique order ID sent to CC Avenue', max_length=100, unique=True)),
                ('tracking_id', models.CharField(blank=True, help_text='CC Avenue tracking ID', max_length=100, null=True)),
                ('bank_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], default='PENDING', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='voc_new_registration.vocnewregistration')),
            ],
            options={
                'verbose_name': 'VOC Registration Payment',
                'verbose_name_plural': 'VOC Registration Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
