# Generated by Django 5.2.10 on 2026-01-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0011_vocnewregistration_registration_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocnewregistration',
            name='registration_no',
        ),
    ]
