# Generated by Django 5.2.10 on 2026-01-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voc_new_registration', '0013_newregistrationbatch_newregistrationcourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newregistration',
            name='course_type',
            field=models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('VOC', 'Vocational'), ('BED', 'Bachelor of Education')], help_text='UG/PG/Vocational/B.ED.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='newregistration',
            name='migration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='voc_registrations/certificates/'),
        ),
        migrations.AddField(
            model_name='newregistration',
            name='registration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='voc_registrations/certificates/'),
        ),
        migrations.AddField(
            model_name='newregistration',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Generated unique registration number', max_length=50, null=True, unique=True),
        ),
    ]
