# Generated by Django 5.2.10 on 2026-02-12 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0009_college_center_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UGBeforeCBCSCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_years', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('part', models.CharField(choices=[('PART1', 'Part I'), ('PART2', 'Part II'), ('PART3', 'Part III')], max_length=10)),
                ('exam_year', models.PositiveIntegerField()),
                ('exam_month_year', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('paper_number', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_type', models.CharField(blank=True, choices=[('HONOURS', 'Honours'), ('SUBSIDIARY', 'Subsidiary'), ('COMPOSITION', 'Composition'), ('GENERAL_STUDIES', 'General Studies'), ('GENERAL', 'General (for Pass Course)')], max_length=20, null=True)),
                ('has_practical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='ug_before_cbcs.ugbeforecbcscourse')),
            ],
            options={
                'verbose_name': 'UG Before CBCS Discipline',
                'verbose_name_plural': 'UG Before CBCS Disciplines',
            },
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exam_type', models.CharField(choices=[('REGULAR', 'Regular'), ('BACK', 'Back/Ex-Regular'), ('IMPROVEMENT', 'Improvement')], default='REGULAR', max_length=20)),
                ('is_ex_regular', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_before_cbcs_exam_centers', to='colleges.college')),
                ('college_at_exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_before_cbcs_exam_registrations', to='colleges.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='ug_before_cbcs.ugbeforecbcsexam')),
            ],
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('grand_total_max', models.IntegerField(blank=True, null=True)),
                ('grand_total_secured', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hons_total_max', models.IntegerField(blank=True, null=True)),
                ('hons_total_secured', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('result_status', models.CharField(blank=True, choices=[('PASS', 'PASS'), ('PASS_WITH_HONS', 'PASS WITH HONS'), ('PROMOTED', 'PROMOTED'), ('FAIL', 'FAIL'), ('ABSENT', 'ABSENT'), ('PENDING', 'PENDING'), ('EXPELLED', 'EXPELLED')], max_length=100, null=True)),
                ('final_result_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_summary', to='ug_before_cbcs.ugbeforecbcsexamregistration')),
            ],
            options={
                'verbose_name': 'UG Before CBCS Exam Result',
                'verbose_name_plural': 'UG Before CBCS Exam Results',
            },
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ug_before_cbcs.ugbeforecbcssession')),
            ],
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_name_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ug_before_cbcs.ugbeforecbcsbatch')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_before_cbcs_students', to='colleges.college')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ug_before_cbcs.ugbeforecbcscourse')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ug_before_cbcs.ugbeforecbcsdiscipline')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ug_before_cbcs.ugbeforecbcssession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ug_before_cbcs_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ugbeforecbcsexamregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='ug_before_cbcs.ugbeforecbcsstudentprofile'),
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSStudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subject_type', models.CharField(choices=[('HONOURS', 'Honours'), ('SUBSIDIARY', 'Subsidiary'), ('COMPOSITION', 'Composition'), ('GENERAL_STUDIES', 'General Studies'), ('GENERAL', 'General (for Pass Course)')], max_length=20)),
                ('theory_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('practical_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('sessional_marks', models.CharField(blank=True, max_length=50, null=True)),
                ('marks_secured', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_marks', models.IntegerField(blank=True, null=True)),
                ('pass_marks', models.IntegerField(blank=True, null=True)),
                ('subject_total_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('subject_result', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='ug_before_cbcs.ugbeforecbcsexamregistration')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ug_before_cbcs.ugbeforecbcssubject')),
            ],
            options={
                'verbose_name': 'UG Before CBCS Student Assessment',
                'verbose_name_plural': 'UG Before CBCS Student Assessments',
            },
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSCourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('part', models.CharField(choices=[('PART1', 'Part I'), ('PART2', 'Part II'), ('PART3', 'Part III')], max_length=10)),
                ('subject_type', models.CharField(choices=[('HONOURS', 'Honours'), ('SUBSIDIARY', 'Subsidiary'), ('COMPOSITION', 'Composition'), ('GENERAL_STUDIES', 'General Studies'), ('GENERAL', 'General (for Pass Course)')], max_length=20)),
                ('theory_max_marks', models.IntegerField(default=100)),
                ('theory_pass_marks', models.IntegerField(default=33)),
                ('practical_max_marks', models.IntegerField(default=0)),
                ('practical_pass_marks', models.IntegerField(default=0)),
                ('aggregate_pass_marks', models.IntegerField(default=33)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='ug_before_cbcs.ugbeforecbcsdiscipline')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ug_before_cbcs.ugbeforecbcssubject')),
            ],
            options={
                'verbose_name': 'UG Before CBCS Course Structure',
                'verbose_name_plural': 'UG Before CBCS Course Structures',
                'unique_together': {('discipline', 'part', 'subject')},
            },
        ),
    ]
