# Generated by Django 5.2.10 on 2026-02-13 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0009_college_center_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UGBeforeCBCSExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Exam name: e.g., B.A. (Hons.) Part-I Exam 2022', max_length=255)),
                ('exam_code', models.CharField(db_index=True, help_text='Unique exam identifier (auto-generated from batch+session+part)', max_length=100, unique=True)),
                ('part', models.CharField(choices=[('PART1', 'Part I'), ('PART2', 'Part II'), ('PART3', 'Part III')], help_text='Part: PART1, PART2, PART3', max_length=10)),
                ('semester_code', models.CharField(blank=True, help_text='Semester code from staging: 1ST, 2ND, 3RD', max_length=50, null=True)),
                ('exam_year', models.PositiveIntegerField(help_text='Exam year: 2022, 2023, etc.')),
                ('exam_month_year', models.CharField(blank=True, help_text='Exam month and year: JANUARY 2023', max_length=100, null=True)),
                ('session_code', models.CharField(blank=True, help_text='Session code from staging: 2021-24', max_length=50, null=True)),
                ('batch_code', models.CharField(blank=True, help_text='Batch code from staging: 2021', max_length=50, null=True)),
                ('course_code', models.CharField(blank=True, help_text='Course code: BA, BSC, BCOM', max_length=50, null=True)),
                ('discipline_code', models.CharField(blank=True, help_text='Discipline code: PSY, HIN, PHY', max_length=50, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UG Before CBCS Exam',
                'verbose_name_plural': 'UG Before CBCS Exams',
                'indexes': [models.Index(fields=['exam_code'], name='ug_before_c_exam_co_7c4528_idx'), models.Index(fields=['part', 'exam_year'], name='ug_before_c_part_231ab7_idx'), models.Index(fields=['batch_code', 'session_code'], name='ug_before_c_batch_c_502216_idx')],
            },
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSStudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('registration_no', models.CharField(db_index=True, help_text='College Registration Number (college_reg_no from staging)', max_length=100, unique=True)),
                ('roll_no', models.CharField(blank=True, help_text='College Roll Number (college_roll_no from staging)', max_length=100, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_name_hindi', models.CharField(blank=True, max_length=255, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, help_text='Course code: BA, BSC, BCOM, etc.', max_length=50, null=True)),
                ('discipline_code', models.CharField(blank=True, help_text='Discipline code: PSY, HIN, PHY, etc.', max_length=50, null=True)),
                ('source_user_id', models.CharField(blank=True, help_text='Original user_id from staging', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_before_cbcs_students', to='colleges.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ug_before_cbcs_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UG Before CBCS Student Profile',
                'verbose_name_plural': 'UG Before CBCS Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='UGBeforeCBCSStudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paper_code', models.CharField(db_index=True, help_text='Paper code from staging', max_length=100)),
                ('subject_code', models.CharField(blank=True, help_text='Subject code from staging', max_length=50, null=True)),
                ('subject_name', models.CharField(blank=True, help_text='Full subject/paper name', max_length=500, null=True)),
                ('temp_paper_code', models.CharField(blank=True, help_text='Temporary paper code from staging', max_length=50, null=True)),
                ('paper_code_correction', models.CharField(blank=True, help_text='Paper code correction from staging', max_length=100, null=True)),
                ('subject_code_correction', models.CharField(blank=True, help_text='Subject code correction from staging', max_length=100, null=True)),
                ('paper_type_code', models.CharField(blank=True, help_text='Paper type code from staging (HONS, SUB, etc.)', max_length=50, null=True)),
                ('exam_type', models.CharField(blank=True, help_text='Exam type: REGULAR, BACK, IMPROVEMENT', max_length=50, null=True)),
                ('exam_type_his', models.CharField(blank=True, help_text='Exam type history from staging', max_length=255, null=True)),
                ('is_ex_regular', models.BooleanField(default=False, help_text='Is Ex-Regular student (from ExRegular_chk)')),
                ('status', models.CharField(blank=True, help_text='Status from staging', max_length=50, null=True)),
                ('theory', models.CharField(blank=True, help_text='Theory marks (can be numeric or ABS, UFM, etc.)', max_length=50, null=True)),
                ('practical', models.CharField(blank=True, help_text='Practical marks (pra from staging)', max_length=50, null=True)),
                ('sessional', models.CharField(blank=True, help_text='Sessional marks', max_length=50, null=True)),
                ('mark_secured', models.CharField(blank=True, help_text='Marks secured (can be numeric or text)', max_length=50, null=True)),
                ('mark_secured_history', models.CharField(blank=True, help_text='Mark secured history from staging', max_length=50, null=True)),
                ('subject_total_mark', models.CharField(blank=True, help_text='Subject total mark', max_length=50, null=True)),
                ('maximum_mark', models.CharField(blank=True, help_text='Maximum marks for this subject', max_length=50, null=True)),
                ('pass_mark', models.CharField(blank=True, help_text='Pass marks for this subject', max_length=50, null=True)),
                ('subject_result', models.CharField(blank=True, help_text='Subject result: PASS, FAIL, etc.', max_length=50, null=True)),
                ('subject_result_1', models.CharField(blank=True, help_text='Subject result variant 1 from staging', max_length=50, null=True)),
                ('subject_result_2', models.CharField(blank=True, help_text='Subject result variant 2 from staging', max_length=50, null=True)),
                ('sub_reult_com', models.CharField(blank=True, help_text='Subject result combined from staging', max_length=50, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('grace_chk', models.CharField(blank=True, help_text='Grace marks check from staging', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, help_text='Remarks from staging', max_length=255, null=True)),
                ('student_check', models.CharField(blank=True, help_text='Student check flag from staging', max_length=50, null=True)),
                ('grand_total_mark', models.CharField(blank=True, help_text='Grand total maximum marks', max_length=50, null=True)),
                ('total_secured_mark', models.CharField(blank=True, help_text='Total secured marks', max_length=50, null=True)),
                ('total_secured_mark_1', models.CharField(blank=True, help_text='Total secured marks variant 1 from staging', max_length=50, null=True)),
                ('total_secured_mark_2', models.CharField(blank=True, help_text='Total secured marks variant 2 from staging', max_length=50, null=True)),
                ('hon', models.CharField(blank=True, help_text='Honours indicator/total from staging', max_length=50, null=True)),
                ('total_per', models.CharField(blank=True, help_text='Total percentage from staging', max_length=50, null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade from staging', max_length=50, null=True)),
                ('final_result', models.CharField(blank=True, help_text='Final result: PASS, FAIL, PASS WITH HONS, etc.', max_length=100, null=True)),
                ('agreegate', models.CharField(blank=True, help_text='Aggregate/Division (typo from staging preserved)', max_length=100, null=True)),
                ('aggregate_hindi', models.TextField(blank=True, help_text='Aggregate in Hindi from staging', null=True)),
                ('record_status', models.CharField(blank=True, help_text='Record status from staging', max_length=50, null=True)),
                ('record_status_check', models.CharField(blank=True, help_text='Record status check from staging', max_length=50, null=True)),
                ('subject_count', models.CharField(blank=True, help_text='Subject count from staging', max_length=50, null=True)),
                ('source_id', models.CharField(blank=True, help_text='Original id from staging', max_length=50, null=True)),
                ('registration_no', models.CharField(blank=True, db_index=True, help_text='Denormalized registration number for faster lookups', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ug_before_cbcs.ugbeforecbcsexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ug_before_cbcs.ugbeforecbcsstudentprofile')),
            ],
            options={
                'verbose_name': 'UG Before CBCS Student Result',
                'verbose_name_plural': 'UG Before CBCS Student Results',
            },
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentprofile',
            index=models.Index(fields=['registration_no'], name='ug_before_c_registr_cdd21a_idx'),
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentprofile',
            index=models.Index(fields=['roll_no'], name='ug_before_c_roll_no_aa00ad_idx'),
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentprofile',
            index=models.Index(fields=['college', 'course_code'], name='ug_before_c_college_12e313_idx'),
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentresult',
            index=models.Index(fields=['student', 'exam'], name='ug_before_c_student_02cb15_idx'),
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentresult',
            index=models.Index(fields=['exam', 'paper_code'], name='ug_before_c_exam_id_0506a3_idx'),
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentresult',
            index=models.Index(fields=['registration_no', 'paper_code'], name='ug_before_c_registr_552ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='ugbeforecbcsstudentresult',
            index=models.Index(fields=['paper_code'], name='ug_before_c_paper_c_1c8847_idx'),
        ),
    ]
