# Generated by Django 5.2.10 on 2026-02-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug_before_cbcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ugbeforecbcsexam',
            name='centre_name',
            field=models.CharField(blank=True, help_text='Examination centre name', max_length=255, null=True),
        ),
    ]
