# Generated by Django 5.2.10 on 2026-02-27 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug_before_cbcs', '0002_ugbeforecbcsexam_centre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGBeforeCBCSStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.JSONField(help_text='The statistics JSON structure')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UG Before CBCS Statistics',
                'verbose_name_plural': 'UG Before CBCS Statistics',
            },
        ),
    ]
