# Generated by Django 5.2.10 on 2026-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ug_before_cbcs', '0003_ugbeforecbcsstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugbeforecbcsstatistics',
            name='data',
            field=models.JSONField(blank=True, help_text='The statistics JSON structure', null=True),
        ),
    ]
