# Generated by Django 5.2.10 on 2026-02-27 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('ug_before_cbcs', '0004_alter_ugbeforecbcsstatistics_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGBeforeCBCSExamCenterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('center_name', models.CharField(help_text='Name of the examination center for this college', max_length=255)),
                ('center_code', models.CharField(blank=True, help_text='Optional center code', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ug_before_cbcs_center_mappings', to='colleges.college')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_mappings', to='ug_before_cbcs.ugbeforecbcsexam')),
            ],
            options={
                'verbose_name': 'UG Before CBCS Exam Center Mapping',
                'verbose_name_plural': 'UG Before CBCS Exam Center Mappings',
                'unique_together': {('exam', 'college')},
            },
        ),
    ]
