# Generated by Django 5.2.10 on 2026-03-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('ug_before_cbcs', '0005_ugbeforecbcsexamcentermapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ugbeforecbcsexamcentermapping',
            old_name='college',
            new_name='student_college',
        ),
        migrations.AddField(
            model_name='ugbeforecbcsexamcentermapping',
            name='center_college',
            field=models.ForeignKey(blank=True, help_text='The college that acts as the examination center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ug_before_cbcs_as_center_mappings', to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='ugbeforecbcsexamcentermapping',
            name='center_name',
            field=models.CharField(blank=True, help_text='Fallback center name if center_college is not set', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ugbeforecbcsexamcentermapping',
            unique_together={('exam', 'student_college')},
        ),
    ]
