# Generated by Django 5.2.10 on 2026-03-02 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0009_college_center_code'),
        ('ug_before_cbcs', '0006_alter_ugbeforecbcsexamcentermapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugbeforecbcsexamcentermapping',
            name='student_college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ug_before_cbcs_student_center_mappings', to='colleges.college'),
        ),
    ]
